FROM ubuntu:oracular
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN apt-get update
RUN apt-get -y install golang-1.23 eg egbootstrap podman netavark rsync vim dput devscripts dh-make dput uidmap dbus-user-session git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
RUN apt-get -y install snapd duckdb

RUN ln -s /usr/lib/go-1.23/bin/go /usr/local/bin/go

# RUN snap install flutter --classic

RUN systemd-sysusers
RUN systemd-tmpfiles --create

