FROM ubuntu:resolute
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "cache buster 4f1c7a3e-9b0d-4a2e-8f3a-6c2e1d9b7a41"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo podman netavark rsync vim dput devscripts dh-make git uidmap dbus-user-session tree python3 python3-venv
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN echo "cache buster 4f1c7a3e-9b0d-4a2e-8f3a-6c2e1d9b7a42"
RUN apt-get update && apt-get -y install golang-1.26 egworkload cargo rustc lld

RUN ln -s /usr/lib/go-1.26/bin/go /usr/local/bin/go
