//go:build !genieql.ignore
// +build !genieql.ignore

package meta

import (
	"context"
	"database/sql"
	"math"
	"time"

	"github.com/google/uuid"
	"github.com/retrovibed/retrovibed/shallows/internal/ducktype"
	"github.com/retrovibed/retrovibed/shallows/internal/sqlx"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto graph -o genieql.gen.go
// invoked by go generate @ retrovibed/00.duckdb.setup.go line 5

// Daemon generated by genieql
type Daemon struct {
	CreatedAt   time.Time `json:"created_at"`
	Default     bool      `json:"default"`
	Description string    `json:"description"`
	Downloads   bool      `json:"downloads"`
	Hostname    string    `json:"hostname"`
	ID          string    `json:"id"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Wireguard generated by genieql
type Wireguard struct {
	CreatedAt    time.Time `json:"created_at"`
	Default      bool      `json:"default"`
	Description  string    `json:"description"`
	DNSRateLimit uint32    `json:"dns_rate_limit"`
	ID           string    `json:"id"`
	Port         uint16    `json:"port"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Authz generated by genieql
type Authz struct {
	BillingModify   bool      `json:"billing_modify"`
	BillingRead     bool      `json:"billing_read"`
	CommunityModify bool      `json:"community_modify"`
	CreatedAt       time.Time `json:"created_at"`
	ID              string    `json:"id"`
	LibraryModify   bool      `json:"library_modify"`
	LibraryRead     bool      `json:"library_read"`
	ProfileID       string    `json:"profile_id"`
	UpdatedAt       time.Time `json:"updated_at"`
	Usermanagement  bool      `json:"usermanagement"`
}

// ConsumedToken generated by genieql
type ConsumedToken struct {
	CreatedAt    time.Time `json:"created_at"`
	ID           string    `json:"id"`
	Token        string    `json:"token"`
	TombstonedAt time.Time `json:"tombstoned_at"`
}

// Profile generated by genieql
type Profile struct {
	CreatedAt                 time.Time `json:"created_at"`
	DisabledAt                time.Time `json:"disabled_at"`
	DisabledManuallyAt        time.Time `json:"disabled_manually_at"`
	DisabledPendingApprovalAt time.Time `json:"disabled_pending_approval_at"`
	Display                   string    `json:"display"`
	ID                        string    `json:"id"`
	SessionWatermark          string    `json:"session_watermark"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

// DaemonScanner scanner interface.
type DaemonScanner interface {
	Scan(i *Daemon) error
	Next() bool
	Close() error
	Err() error
}

type errDaemonScanner struct {
	e error
}

func (t errDaemonScanner) Scan(i *Daemon) error {
	return t.e
}

func (t errDaemonScanner) Next() bool {
	return false
}

func (t errDaemonScanner) Err() error {
	return t.e
}

func (t errDaemonScanner) Close() error {
	return nil
}

// DaemonScannerStaticColumns generated by genieql
const DaemonScannerStaticColumns = `meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at"`

// NewDaemonScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewDaemonScannerStatic(rows *sql.Rows, err error) DaemonScanner {
	if err != nil {
		return errDaemonScanner{e: err}
	}

	return daemonScannerStatic{
		Rows: rows,
	}
}

// daemonScannerStatic generated by genieql
type daemonScannerStatic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t daemonScannerStatic) Scan(i *Daemon) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullBool
		c2 sql.NullString
		c3 sql.NullBool
		c4 sql.NullString
		c5 sql.NullString
		c6 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.CreatedAt = tmp
	default:
		i.CreatedAt = c0.Time
	}

	if c1.Valid {
		tmp := c1.Bool
		i.Default = tmp
	}

	if c2.Valid {
		tmp := string(c2.String)
		i.Description = tmp
	}

	if c3.Valid {
		tmp := c3.Bool
		i.Downloads = tmp
	}

	if c4.Valid {
		tmp := string(c4.String)
		i.Hostname = tmp
	}

	if c5.Valid {
		if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	switch c6.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.UpdatedAt = tmp
	default:
		i.UpdatedAt = c6.Time
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t daemonScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t daemonScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t daemonScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewDaemonScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewDaemonScannerStaticRow(row *sql.Row) DaemonScannerStaticRow {
	return DaemonScannerStaticRow{
		row: row,
	}
}

// DaemonScannerStaticRow generated by genieql
type DaemonScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t DaemonScannerStaticRow) Scan(i *Daemon) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullBool
		c2 sql.NullString
		c3 sql.NullBool
		c4 sql.NullString
		c5 sql.NullString
		c6 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.CreatedAt = tmp
	default:
		i.CreatedAt = c0.Time
	}

	if c1.Valid {
		tmp := c1.Bool
		i.Default = tmp
	}

	if c2.Valid {
		tmp := string(c2.String)
		i.Description = tmp
	}

	if c3.Valid {
		tmp := c3.Bool
		i.Downloads = tmp
	}

	if c4.Valid {
		tmp := string(c4.String)
		i.Hostname = tmp
	}

	if c5.Valid {
		if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	switch c6.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.UpdatedAt = tmp
	default:
		i.UpdatedAt = c6.Time
	}

	return nil
}

// Err set an error to return by scan
func (t DaemonScannerStaticRow) Err(err error) DaemonScannerStaticRow {
	t.err = err
	return t
}

// NewDaemonScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewDaemonScannerDynamic(rows *sql.Rows, err error) DaemonScanner {
	if err != nil {
		return errDaemonScanner{e: err}
	}

	return daemonScannerDynamic{
		Rows: rows,
	}
}

// daemonScannerDynamic generated by genieql
type daemonScannerDynamic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t daemonScannerDynamic) Scan(i *Daemon) error {
	const (
		cn0 = "created_at"
		cn1 = "default"
		cn2 = "description"
		cn3 = "downloads"
		cn4 = "hostname"
		cn5 = "id"
		cn6 = "updated_at"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      ducktype.NullTime
		c1      sql.NullBool
		c2      sql.NullString
		c3      sql.NullBool
		c4      sql.NullString
		c5      sql.NullString
		c6      ducktype.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			switch c0.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.CreatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.CreatedAt = tmp
			default:
				i.CreatedAt = c0.Time
			}

		case cn1:
			if c1.Valid {
				tmp := c1.Bool
				i.Default = tmp
			}

		case cn2:
			if c2.Valid {
				tmp := string(c2.String)
				i.Description = tmp
			}

		case cn3:
			if c3.Valid {
				tmp := c3.Bool
				i.Downloads = tmp
			}

		case cn4:
			if c4.Valid {
				tmp := string(c4.String)
				i.Hostname = tmp
			}

		case cn5:
			if c5.Valid {
				if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
					return err
				} else {
					i.ID = uid.String()
				}
			}

		case cn6:
			switch c6.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.UpdatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.UpdatedAt = tmp
			default:
				i.UpdatedAt = c6.Time
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t daemonScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t daemonScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t daemonScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// ConsumedTokenScanner scanner interface.
type ConsumedTokenScanner interface {
	Scan(a *ConsumedToken) error
	Next() bool
	Close() error
	Err() error
}

type errConsumedTokenScanner struct {
	e error
}

func (t errConsumedTokenScanner) Scan(a *ConsumedToken) error {
	return t.e
}

func (t errConsumedTokenScanner) Next() bool {
	return false
}

func (t errConsumedTokenScanner) Err() error {
	return t.e
}

func (t errConsumedTokenScanner) Close() error {
	return nil
}

// ConsumedTokenScannerStaticColumns generated by genieql
const ConsumedTokenScannerStaticColumns = `meta_consumed_tokens."created_at",meta_consumed_tokens."id",meta_consumed_tokens."token",meta_consumed_tokens."tombstoned_at"`

// NewConsumedTokenScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewConsumedTokenScannerStatic(rows *sql.Rows, err error) ConsumedTokenScanner {
	if err != nil {
		return errConsumedTokenScanner{e: err}
	}

	return consumedTokenScannerStatic{
		Rows: rows,
	}
}

// consumedTokenScannerStatic generated by genieql
type consumedTokenScannerStatic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t consumedTokenScannerStatic) Scan(a *ConsumedToken) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullString
		c2 sql.NullString
		c3 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c0.Time
	}

	if c1.Valid {
		if uid, err := uuid.FromBytes([]byte(c1.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c2.Valid {
		tmp := string(c2.String)
		a.Token = tmp
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.TombstonedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.TombstonedAt = tmp
	default:
		a.TombstonedAt = c3.Time
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t consumedTokenScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t consumedTokenScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t consumedTokenScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewConsumedTokenScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewConsumedTokenScannerStaticRow(row *sql.Row) ConsumedTokenScannerStaticRow {
	return ConsumedTokenScannerStaticRow{
		row: row,
	}
}

// ConsumedTokenScannerStaticRow generated by genieql
type ConsumedTokenScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t ConsumedTokenScannerStaticRow) Scan(a *ConsumedToken) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullString
		c2 sql.NullString
		c3 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c0.Time
	}

	if c1.Valid {
		if uid, err := uuid.FromBytes([]byte(c1.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c2.Valid {
		tmp := string(c2.String)
		a.Token = tmp
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.TombstonedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.TombstonedAt = tmp
	default:
		a.TombstonedAt = c3.Time
	}

	return nil
}

// Err set an error to return by scan
func (t ConsumedTokenScannerStaticRow) Err(err error) ConsumedTokenScannerStaticRow {
	t.err = err
	return t
}

// NewConsumedTokenScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewConsumedTokenScannerDynamic(rows *sql.Rows, err error) ConsumedTokenScanner {
	if err != nil {
		return errConsumedTokenScanner{e: err}
	}

	return consumedTokenScannerDynamic{
		Rows: rows,
	}
}

// consumedTokenScannerDynamic generated by genieql
type consumedTokenScannerDynamic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t consumedTokenScannerDynamic) Scan(a *ConsumedToken) error {
	const (
		cn0 = "created_at"
		cn1 = "id"
		cn2 = "token"
		cn3 = "tombstoned_at"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      ducktype.NullTime
		c1      sql.NullString
		c2      sql.NullString
		c3      ducktype.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			switch c0.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.CreatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.CreatedAt = tmp
			default:
				a.CreatedAt = c0.Time
			}

		case cn1:
			if c1.Valid {
				if uid, err := uuid.FromBytes([]byte(c1.String)); err != nil {
					return err
				} else {
					a.ID = uid.String()
				}
			}

		case cn2:
			if c2.Valid {
				tmp := string(c2.String)
				a.Token = tmp
			}

		case cn3:
			switch c3.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.TombstonedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.TombstonedAt = tmp
			default:
				a.TombstonedAt = c3.Time
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t consumedTokenScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t consumedTokenScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t consumedTokenScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// WireguardScanner scanner interface.
type WireguardScanner interface {
	Scan(a *Wireguard) error
	Next() bool
	Close() error
	Err() error
}

type errWireguardScanner struct {
	e error
}

func (t errWireguardScanner) Scan(a *Wireguard) error {
	return t.e
}

func (t errWireguardScanner) Next() bool {
	return false
}

func (t errWireguardScanner) Err() error {
	return t.e
}

func (t errWireguardScanner) Close() error {
	return nil
}

// WireguardScannerStaticColumns generated by genieql
const WireguardScannerStaticColumns = `meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at"`

// NewWireguardScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewWireguardScannerStatic(rows *sql.Rows, err error) WireguardScanner {
	if err != nil {
		return errWireguardScanner{e: err}
	}

	return wireguardScannerStatic{
		Rows: rows,
	}
}

// wireguardScannerStatic generated by genieql
type wireguardScannerStatic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t wireguardScannerStatic) Scan(a *Wireguard) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullBool
		c2 sql.NullString
		c3 sql.NullInt64
		c4 sql.NullString
		c5 sql.NullInt32
		c6 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c0.Time
	}

	if c1.Valid {
		tmp := c1.Bool
		a.Default = tmp
	}

	if c2.Valid {
		tmp := string(c2.String)
		a.Description = tmp
	}

	if c3.Valid {
		tmp := uint32(c3.Int64)
		a.DNSRateLimit = tmp
	}

	if c4.Valid {
		if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c5.Valid {
		tmp := uint16(c5.Int32)
		a.Port = tmp
	}

	switch c6.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.UpdatedAt = tmp
	default:
		a.UpdatedAt = c6.Time
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t wireguardScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t wireguardScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t wireguardScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewWireguardScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewWireguardScannerStaticRow(row *sql.Row) WireguardScannerStaticRow {
	return WireguardScannerStaticRow{
		row: row,
	}
}

// WireguardScannerStaticRow generated by genieql
type WireguardScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t WireguardScannerStaticRow) Scan(a *Wireguard) error {
	var (
		c0 ducktype.NullTime
		c1 sql.NullBool
		c2 sql.NullString
		c3 sql.NullInt64
		c4 sql.NullString
		c5 sql.NullInt32
		c6 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c0.Time
	}

	if c1.Valid {
		tmp := c1.Bool
		a.Default = tmp
	}

	if c2.Valid {
		tmp := string(c2.String)
		a.Description = tmp
	}

	if c3.Valid {
		tmp := uint32(c3.Int64)
		a.DNSRateLimit = tmp
	}

	if c4.Valid {
		if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c5.Valid {
		tmp := uint16(c5.Int32)
		a.Port = tmp
	}

	switch c6.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.UpdatedAt = tmp
	default:
		a.UpdatedAt = c6.Time
	}

	return nil
}

// Err set an error to return by scan
func (t WireguardScannerStaticRow) Err(err error) WireguardScannerStaticRow {
	t.err = err
	return t
}

// NewWireguardScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewWireguardScannerDynamic(rows *sql.Rows, err error) WireguardScanner {
	if err != nil {
		return errWireguardScanner{e: err}
	}

	return wireguardScannerDynamic{
		Rows: rows,
	}
}

// wireguardScannerDynamic generated by genieql
type wireguardScannerDynamic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t wireguardScannerDynamic) Scan(a *Wireguard) error {
	const (
		cn0 = "created_at"
		cn1 = "default"
		cn2 = "description"
		cn3 = "dns_rate_limit"
		cn4 = "id"
		cn5 = "port"
		cn6 = "updated_at"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      ducktype.NullTime
		c1      sql.NullBool
		c2      sql.NullString
		c3      sql.NullInt64
		c4      sql.NullString
		c5      sql.NullInt32
		c6      ducktype.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			switch c0.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.CreatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.CreatedAt = tmp
			default:
				a.CreatedAt = c0.Time
			}

		case cn1:
			if c1.Valid {
				tmp := c1.Bool
				a.Default = tmp
			}

		case cn2:
			if c2.Valid {
				tmp := string(c2.String)
				a.Description = tmp
			}

		case cn3:
			if c3.Valid {
				tmp := uint32(c3.Int64)
				a.DNSRateLimit = tmp
			}

		case cn4:
			if c4.Valid {
				if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
					return err
				} else {
					a.ID = uid.String()
				}
			}

		case cn5:
			if c5.Valid {
				tmp := uint16(c5.Int32)
				a.Port = tmp
			}

		case cn6:
			switch c6.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.UpdatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.UpdatedAt = tmp
			default:
				a.UpdatedAt = c6.Time
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t wireguardScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t wireguardScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t wireguardScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// ProfileScanner scanner interface.
type ProfileScanner interface {
	Scan(i *Profile) error
	Next() bool
	Close() error
	Err() error
}

type errProfileScanner struct {
	e error
}

func (t errProfileScanner) Scan(i *Profile) error {
	return t.e
}

func (t errProfileScanner) Next() bool {
	return false
}

func (t errProfileScanner) Err() error {
	return t.e
}

func (t errProfileScanner) Close() error {
	return nil
}

// ProfileScannerStaticColumns generated by genieql
const ProfileScannerStaticColumns = `meta_profiles."created_at",meta_profiles."disabled_at",meta_profiles."disabled_manually_at",meta_profiles."disabled_pending_approval_at",meta_profiles."display",meta_profiles."id",meta_profiles."session_watermark",meta_profiles."updated_at"`

// NewProfileScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewProfileScannerStatic(rows *sql.Rows, err error) ProfileScanner {
	if err != nil {
		return errProfileScanner{e: err}
	}

	return profileScannerStatic{
		Rows: rows,
	}
}

// profileScannerStatic generated by genieql
type profileScannerStatic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t profileScannerStatic) Scan(i *Profile) error {
	var (
		c0 ducktype.NullTime
		c1 ducktype.NullTime
		c2 ducktype.NullTime
		c3 ducktype.NullTime
		c4 sql.NullString
		c5 sql.NullString
		c6 sql.NullString
		c7 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.CreatedAt = tmp
	default:
		i.CreatedAt = c0.Time
	}

	switch c1.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledAt = tmp
	default:
		i.DisabledAt = c1.Time
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledManuallyAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledManuallyAt = tmp
	default:
		i.DisabledManuallyAt = c2.Time
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledPendingApprovalAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledPendingApprovalAt = tmp
	default:
		i.DisabledPendingApprovalAt = c3.Time
	}

	if c4.Valid {
		tmp := string(c4.String)
		i.Display = tmp
	}

	if c5.Valid {
		if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	if c6.Valid {
		if uid, err := uuid.FromBytes([]byte(c6.String)); err != nil {
			return err
		} else {
			i.SessionWatermark = uid.String()
		}
	}

	switch c7.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.UpdatedAt = tmp
	default:
		i.UpdatedAt = c7.Time
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t profileScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t profileScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t profileScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewProfileScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewProfileScannerStaticRow(row *sql.Row) ProfileScannerStaticRow {
	return ProfileScannerStaticRow{
		row: row,
	}
}

// ProfileScannerStaticRow generated by genieql
type ProfileScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t ProfileScannerStaticRow) Scan(i *Profile) error {
	var (
		c0 ducktype.NullTime
		c1 ducktype.NullTime
		c2 ducktype.NullTime
		c3 ducktype.NullTime
		c4 sql.NullString
		c5 sql.NullString
		c6 sql.NullString
		c7 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7); err != nil {
		return err
	}

	switch c0.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.CreatedAt = tmp
	default:
		i.CreatedAt = c0.Time
	}

	switch c1.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledAt = tmp
	default:
		i.DisabledAt = c1.Time
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledManuallyAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledManuallyAt = tmp
	default:
		i.DisabledManuallyAt = c2.Time
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.DisabledPendingApprovalAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.DisabledPendingApprovalAt = tmp
	default:
		i.DisabledPendingApprovalAt = c3.Time
	}

	if c4.Valid {
		tmp := string(c4.String)
		i.Display = tmp
	}

	if c5.Valid {
		if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	if c6.Valid {
		if uid, err := uuid.FromBytes([]byte(c6.String)); err != nil {
			return err
		} else {
			i.SessionWatermark = uid.String()
		}
	}

	switch c7.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		i.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		i.UpdatedAt = tmp
	default:
		i.UpdatedAt = c7.Time
	}

	return nil
}

// Err set an error to return by scan
func (t ProfileScannerStaticRow) Err(err error) ProfileScannerStaticRow {
	t.err = err
	return t
}

// NewProfileScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewProfileScannerDynamic(rows *sql.Rows, err error) ProfileScanner {
	if err != nil {
		return errProfileScanner{e: err}
	}

	return profileScannerDynamic{
		Rows: rows,
	}
}

// profileScannerDynamic generated by genieql
type profileScannerDynamic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t profileScannerDynamic) Scan(i *Profile) error {
	const (
		cn0 = "created_at"
		cn1 = "disabled_at"
		cn2 = "disabled_manually_at"
		cn3 = "disabled_pending_approval_at"
		cn4 = "display"
		cn5 = "id"
		cn6 = "session_watermark"
		cn7 = "updated_at"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      ducktype.NullTime
		c1      ducktype.NullTime
		c2      ducktype.NullTime
		c3      ducktype.NullTime
		c4      sql.NullString
		c5      sql.NullString
		c6      sql.NullString
		c7      ducktype.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		case cn7:
			dst = append(dst, &c7)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			switch c0.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.CreatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.CreatedAt = tmp
			default:
				i.CreatedAt = c0.Time
			}

		case cn1:
			switch c1.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.DisabledAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.DisabledAt = tmp
			default:
				i.DisabledAt = c1.Time
			}

		case cn2:
			switch c2.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.DisabledManuallyAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.DisabledManuallyAt = tmp
			default:
				i.DisabledManuallyAt = c2.Time
			}

		case cn3:
			switch c3.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.DisabledPendingApprovalAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.DisabledPendingApprovalAt = tmp
			default:
				i.DisabledPendingApprovalAt = c3.Time
			}

		case cn4:
			if c4.Valid {
				tmp := string(c4.String)
				i.Display = tmp
			}

		case cn5:
			if c5.Valid {
				if uid, err := uuid.FromBytes([]byte(c5.String)); err != nil {
					return err
				} else {
					i.ID = uid.String()
				}
			}

		case cn6:
			if c6.Valid {
				if uid, err := uuid.FromBytes([]byte(c6.String)); err != nil {
					return err
				} else {
					i.SessionWatermark = uid.String()
				}
			}

		case cn7:
			switch c7.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				i.UpdatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				i.UpdatedAt = tmp
			default:
				i.UpdatedAt = c7.Time
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t profileScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t profileScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t profileScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// AuthzScanner scanner interface.
type AuthzScanner interface {
	Scan(a *Authz) error
	Next() bool
	Close() error
	Err() error
}

type errAuthzScanner struct {
	e error
}

func (t errAuthzScanner) Scan(a *Authz) error {
	return t.e
}

func (t errAuthzScanner) Next() bool {
	return false
}

func (t errAuthzScanner) Err() error {
	return t.e
}

func (t errAuthzScanner) Close() error {
	return nil
}

// AuthzScannerStaticColumns generated by genieql
const AuthzScannerStaticColumns = `authz_meta."billing_modify",authz_meta."billing_read",authz_meta."community_modify",authz_meta."created_at",authz_meta."id",authz_meta."library_modify",authz_meta."library_read",authz_meta."profile_id",authz_meta."updated_at",authz_meta."usermanagement"`

// NewAuthzScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewAuthzScannerStatic(rows *sql.Rows, err error) AuthzScanner {
	if err != nil {
		return errAuthzScanner{e: err}
	}

	return authzScannerStatic{
		Rows: rows,
	}
}

// authzScannerStatic generated by genieql
type authzScannerStatic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t authzScannerStatic) Scan(a *Authz) error {
	var (
		c0 sql.NullBool
		c1 sql.NullBool
		c2 sql.NullBool
		c3 ducktype.NullTime
		c4 sql.NullString
		c5 sql.NullBool
		c6 sql.NullBool
		c7 sql.NullString
		c8 ducktype.NullTime
		c9 sql.NullBool
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9); err != nil {
		return err
	}

	if c0.Valid {
		tmp := c0.Bool
		a.BillingModify = tmp
	}

	if c1.Valid {
		tmp := c1.Bool
		a.BillingRead = tmp
	}

	if c2.Valid {
		tmp := c2.Bool
		a.CommunityModify = tmp
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c3.Time
	}

	if c4.Valid {
		if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c5.Valid {
		tmp := c5.Bool
		a.LibraryModify = tmp
	}

	if c6.Valid {
		tmp := c6.Bool
		a.LibraryRead = tmp
	}

	if c7.Valid {
		if uid, err := uuid.FromBytes([]byte(c7.String)); err != nil {
			return err
		} else {
			a.ProfileID = uid.String()
		}
	}

	switch c8.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.UpdatedAt = tmp
	default:
		a.UpdatedAt = c8.Time
	}

	if c9.Valid {
		tmp := c9.Bool
		a.Usermanagement = tmp
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t authzScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t authzScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t authzScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewAuthzScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewAuthzScannerStaticRow(row *sql.Row) AuthzScannerStaticRow {
	return AuthzScannerStaticRow{
		row: row,
	}
}

// AuthzScannerStaticRow generated by genieql
type AuthzScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t AuthzScannerStaticRow) Scan(a *Authz) error {
	var (
		c0 sql.NullBool
		c1 sql.NullBool
		c2 sql.NullBool
		c3 ducktype.NullTime
		c4 sql.NullString
		c5 sql.NullBool
		c6 sql.NullBool
		c7 sql.NullString
		c8 ducktype.NullTime
		c9 sql.NullBool
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9); err != nil {
		return err
	}

	if c0.Valid {
		tmp := c0.Bool
		a.BillingModify = tmp
	}

	if c1.Valid {
		tmp := c1.Bool
		a.BillingRead = tmp
	}

	if c2.Valid {
		tmp := c2.Bool
		a.CommunityModify = tmp
	}

	switch c3.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.CreatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.CreatedAt = tmp
	default:
		a.CreatedAt = c3.Time
	}

	if c4.Valid {
		if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
			return err
		} else {
			a.ID = uid.String()
		}
	}

	if c5.Valid {
		tmp := c5.Bool
		a.LibraryModify = tmp
	}

	if c6.Valid {
		tmp := c6.Bool
		a.LibraryRead = tmp
	}

	if c7.Valid {
		if uid, err := uuid.FromBytes([]byte(c7.String)); err != nil {
			return err
		} else {
			a.ProfileID = uid.String()
		}
	}

	switch c8.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		a.UpdatedAt = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		a.UpdatedAt = tmp
	default:
		a.UpdatedAt = c8.Time
	}

	if c9.Valid {
		tmp := c9.Bool
		a.Usermanagement = tmp
	}

	return nil
}

// Err set an error to return by scan
func (t AuthzScannerStaticRow) Err(err error) AuthzScannerStaticRow {
	t.err = err
	return t
}

// NewAuthzScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewAuthzScannerDynamic(rows *sql.Rows, err error) AuthzScanner {
	if err != nil {
		return errAuthzScanner{e: err}
	}

	return authzScannerDynamic{
		Rows: rows,
	}
}

// authzScannerDynamic generated by genieql
type authzScannerDynamic struct {
	Rows *sql.Rows `json:"rows"`
}

// Scan generated by genieql
func (t authzScannerDynamic) Scan(a *Authz) error {
	const (
		cn0 = "billing_modify"
		cn1 = "billing_read"
		cn2 = "community_modify"
		cn3 = "created_at"
		cn4 = "id"
		cn5 = "library_modify"
		cn6 = "library_read"
		cn7 = "profile_id"
		cn8 = "updated_at"
		cn9 = "usermanagement"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      sql.NullBool
		c1      sql.NullBool
		c2      sql.NullBool
		c3      ducktype.NullTime
		c4      sql.NullString
		c5      sql.NullBool
		c6      sql.NullBool
		c7      sql.NullString
		c8      ducktype.NullTime
		c9      sql.NullBool
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		case cn7:
			dst = append(dst, &c7)
		case cn8:
			dst = append(dst, &c8)
		case cn9:
			dst = append(dst, &c9)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if c0.Valid {
				tmp := c0.Bool
				a.BillingModify = tmp
			}

		case cn1:
			if c1.Valid {
				tmp := c1.Bool
				a.BillingRead = tmp
			}

		case cn2:
			if c2.Valid {
				tmp := c2.Bool
				a.CommunityModify = tmp
			}

		case cn3:
			switch c3.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.CreatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.CreatedAt = tmp
			default:
				a.CreatedAt = c3.Time
			}

		case cn4:
			if c4.Valid {
				if uid, err := uuid.FromBytes([]byte(c4.String)); err != nil {
					return err
				} else {
					a.ID = uid.String()
				}
			}

		case cn5:
			if c5.Valid {
				tmp := c5.Bool
				a.LibraryModify = tmp
			}

		case cn6:
			if c6.Valid {
				tmp := c6.Bool
				a.LibraryRead = tmp
			}

		case cn7:
			if c7.Valid {
				if uid, err := uuid.FromBytes([]byte(c7.String)); err != nil {
					return err
				} else {
					a.ProfileID = uid.String()
				}
			}

		case cn8:
			switch c8.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				a.UpdatedAt = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				a.UpdatedAt = tmp
			default:
				a.UpdatedAt = c8.Time
			}

		case cn9:
			if c9.Valid {
				tmp := c9.Bool
				a.Usermanagement = tmp
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t authzScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t authzScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t authzScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// ConsumedTokenFindByCreatedAt generated by genieql
func ConsumedTokenFindByCreatedAt(ctx context.Context, q sqlx.Queryer, c ducktype.NullTime) ConsumedTokenScannerStaticRow {
	const query = `SELECT "created_at","id","token","tombstoned_at" FROM "meta_consumed_tokens" WHERE "created_at" = $1`
	return NewConsumedTokenScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// ConsumedTokenFindByID generated by genieql
func ConsumedTokenFindByID(ctx context.Context, q sqlx.Queryer, c sql.NullString) ConsumedTokenScannerStaticRow {
	const query = `SELECT "created_at","id","token","tombstoned_at" FROM "meta_consumed_tokens" WHERE "id" = $1`
	return NewConsumedTokenScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// ConsumedTokenFindByToken generated by genieql
func ConsumedTokenFindByToken(ctx context.Context, q sqlx.Queryer, c sql.NullString) ConsumedTokenScannerStaticRow {
	const query = `SELECT "created_at","id","token","tombstoned_at" FROM "meta_consumed_tokens" WHERE "token" = $1`
	return NewConsumedTokenScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// ConsumedTokenFindByTombstonedAt generated by genieql
func ConsumedTokenFindByTombstonedAt(ctx context.Context, q sqlx.Queryer, c ducktype.NullTime) ConsumedTokenScannerStaticRow {
	const query = `SELECT "created_at","id","token","tombstoned_at" FROM "meta_consumed_tokens" WHERE "tombstoned_at" = $1`
	return NewConsumedTokenScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// ProfileInsertWithIDStaticColumns generated by genieql
const ProfileInsertWithIDStaticColumns = `DEFAULT,DEFAULT,DEFAULT,DEFAULT,$1,$2,DEFAULT,DEFAULT`

// ProfileInsertWithIDExplode generated by genieql
func ProfileInsertWithIDExplode(a *Profile) ([]interface{}, error) {
	var (
		c0 sql.NullString // display
		c1 sql.NullString // id
	)

	c0.Valid = true
	c0.String = a.Display

	c1.Valid = true
	c1.String = a.ID

	return []interface{}{c0, c1}, nil
}

// ProfileInsertWithID generated by genieql
func ProfileInsertWithID(ctx context.Context, q sqlx.Queryer, a Profile) ProfileScannerStaticRow {
	const query = `INSERT INTO "meta_profiles" ("created_at","disabled_at","disabled_manually_at","disabled_pending_approval_at","display","id","session_watermark","updated_at") VALUES (DEFAULT,DEFAULT,DEFAULT,DEFAULT,$1,$2,DEFAULT,DEFAULT) ON CONFLICT (id) DO UPDATE SET updated_at = DEFAULT RETURNING "created_at","disabled_at","disabled_manually_at","disabled_pending_approval_at","display","id","session_watermark","updated_at"`
	var (
		c0 sql.NullString // display
		c1 sql.NullString
	)
	c0.Valid = true
	c0.String = a.Display
	c1.Valid = true
	c1.String = a.ID // id
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1))
}

// DaemonFindByLatestUpdated generated by genieql
func DaemonFindByLatestUpdated(ctx context.Context, q sqlx.Queryer) DaemonScannerStaticRow {
	const query = `SELECT meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at" FROM meta_daemons ORDER BY updated_at DESC LIMIT 1`
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query))
}

// DaemonFindDefault generated by genieql
func DaemonFindDefault(ctx context.Context, q sqlx.Queryer) DaemonScannerStaticRow {
	const query = `SELECT meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at" FROM meta_daemons WHERE "default" LIMIT 1`
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query))
}

// DaemonTouch generated by genieql
func DaemonTouch(ctx context.Context, q sqlx.Queryer, id string) DaemonScannerStaticRow {
	const query = `UPDATE meta_daemons SET updated_at = NOW(), "default" = 'f' WHERE "default"; UPDATE meta_daemons SET updated_at = NOW(), "default" = 't' WHERE "id" = $1 RETURNING meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// DaemonDownload generated by genieql
func DaemonDownload(ctx context.Context, q sqlx.Queryer, id string) DaemonScannerStaticRow {
	const query = `UPDATE meta_daemons SET updated_at = NOW(), downloads = 'f' WHERE downloads; UPDATE meta_daemons SET updated_at = NOW(), downloads = 't' WHERE "id" = $1 RETURNING meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// DaemonFindByDownload generated by genieql
func DaemonFindByDownload(ctx context.Context, q sqlx.Queryer) DaemonScannerStaticRow {
	const query = `SELECT meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at" FROM meta_daemons WHERE downloads LIMIT 1`
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query))
}

// DaemonDeleteByID generated by genieql
func DaemonDeleteByID(ctx context.Context, q sqlx.Queryer, id string) DaemonScannerStaticRow {
	const query = `DELETE FROM meta_daemons WHERE "id" = $1 RETURNING meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// ProfileEnable generated by genieql
func ProfileEnable(ctx context.Context, q sqlx.Queryer, id string) ProfileScannerStaticRow {
	const query = `UPDATE meta_profiles SET disabled_at = DEFAULT, disabled_manually_at = DEFAULT, disabled_pending_approval_at = 'infinity' WHERE "meta_profiles"."id" = $1 RETURNING meta_profiles."created_at",meta_profiles."disabled_at",meta_profiles."disabled_manually_at",meta_profiles."disabled_pending_approval_at",meta_profiles."display",meta_profiles."id",meta_profiles."session_watermark",meta_profiles."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// DaemonInsertWithDefaultsStaticColumns generated by genieql
const DaemonInsertWithDefaultsStaticColumns = `DEFAULT,$1,$2,$3,$4,$5,DEFAULT`

// DaemonInsertWithDefaultsExplode generated by genieql
func DaemonInsertWithDefaultsExplode(a *Daemon) ([]interface{}, error) {
	var (
		c0 sql.NullBool   // default
		c1 sql.NullString // description
		c2 sql.NullBool   // downloads
		c3 sql.NullString // hostname
		c4 sql.NullString // id
	)

	c0.Valid = true
	c0.Bool = a.Default

	c1.Valid = true
	c1.String = a.Description

	c2.Valid = true
	c2.Bool = a.Downloads

	c3.Valid = true
	c3.String = a.Hostname

	c4.Valid = true
	c4.String = a.ID

	return []interface{}{c0, c1, c2, c3, c4}, nil
}

// DaemonInsertWithDefaults generated by genieql
func DaemonInsertWithDefaults(ctx context.Context, q sqlx.Queryer, a Daemon) DaemonScannerStaticRow {
	const query = `INSERT INTO "meta_daemons" ("created_at","default","description","downloads","hostname","id","updated_at") VALUES (DEFAULT,$1,$2,$3,$4,$5,DEFAULT) ON CONFLICT (id) DO UPDATE SET updated_at = DEFAULT RETURNING "created_at","default","description","downloads","hostname","id","updated_at"`
	var (
		c0 sql.NullBool   // default
		c1 sql.NullString // description
		c2 sql.NullBool   // downloads
		c3 sql.NullString // hostname
		c4 sql.NullString
	)
	c0.Valid = true
	c0.Bool = a.Default
	c1.Valid = true
	c1.String = a.Description
	c2.Valid = true
	c2.Bool = a.Downloads
	c3.Valid = true
	c3.String = a.Hostname
	c4.Valid = true
	c4.String = a.ID // id
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4))
}

// ProfileDisableByID generated by genieql
func ProfileDisableByID(ctx context.Context, q sqlx.Queryer, id string) ProfileScannerStaticRow {
	const query = `UPDATE meta_profiles SET updated_at = NOW(), disabled_manually_at = NOW(), disabled_pending_approval_at = 'infinity' WHERE "id" = $1 RETURNING meta_profiles."created_at",meta_profiles."disabled_at",meta_profiles."disabled_manually_at",meta_profiles."disabled_pending_approval_at",meta_profiles."display",meta_profiles."id",meta_profiles."session_watermark",meta_profiles."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// ConsumedTokenInsertWithDefaultsStaticColumns generated by genieql
const ConsumedTokenInsertWithDefaultsStaticColumns = `DEFAULT,$1,$2,$3`

// ConsumedTokenInsertWithDefaultsExplode generated by genieql
func ConsumedTokenInsertWithDefaultsExplode(a *ConsumedToken) ([]interface{}, error) {
	var (
		c0 sql.NullString    // id
		c1 sql.NullString    // token
		c2 ducktype.NullTime // tombstoned_at
	)

	c0.Valid = true
	c0.String = a.ID

	c1.Valid = true
	c1.String = a.Token

	switch ts := a.TombstonedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c2.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c2.NegativeInfinity()
	default:
		c2.Status = ducktype.Present
		c2.Time = a.TombstonedAt
	}

	return []interface{}{c0, c1, c2}, nil
}

// ConsumedTokenInsertWithDefaults generated by genieql
func ConsumedTokenInsertWithDefaults(ctx context.Context, q sqlx.Queryer, a ConsumedToken) ConsumedTokenScannerStaticRow {
	const query = `INSERT INTO "meta_consumed_tokens" ("created_at","id","token","tombstoned_at") VALUES (DEFAULT,$1,$2,$3) RETURNING "created_at","id","token","tombstoned_at"`
	var (
		c0 sql.NullString // id
		c1 sql.NullString // token
		c2 ducktype.NullTime
	)
	c0.Valid = true
	c0.String = a.ID
	c1.Valid = true
	c1.String = a.Token
	switch ts := a.TombstonedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c2.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c2.NegativeInfinity()
	default:
		c2.Status = ducktype.Present
		c2.Time = a.TombstonedAt
	} // tombstoned_at
	return NewConsumedTokenScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2))
}

// ProfileInsertWithDefaultsStaticColumns generated by genieql
const ProfileInsertWithDefaultsStaticColumns = `DEFAULT,DEFAULT,DEFAULT,DEFAULT,$1,DEFAULT,DEFAULT,DEFAULT`

// ProfileInsertWithDefaultsExplode generated by genieql
func ProfileInsertWithDefaultsExplode(a *Profile) ([]interface{}, error) {
	var (
		c0 sql.NullString // display
	)

	c0.Valid = true
	c0.String = a.Display

	return []interface{}{c0}, nil
}

// ProfileInsertWithDefaults generated by genieql
func ProfileInsertWithDefaults(ctx context.Context, q sqlx.Queryer, a Profile) ProfileScannerStaticRow {
	const query = `INSERT INTO "meta_profiles" ("created_at","disabled_at","disabled_manually_at","disabled_pending_approval_at","display","id","session_watermark","updated_at") VALUES (DEFAULT,DEFAULT,DEFAULT,DEFAULT,$1,DEFAULT,DEFAULT,DEFAULT) ON CONFLICT (id) DO UPDATE SET updated_at = DEFAULT RETURNING "created_at","disabled_at","disabled_manually_at","disabled_pending_approval_at","display","id","session_watermark","updated_at"`
	var c0 sql.NullString
	c0.Valid = true
	c0.String = a.Display // display
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// DaemonUpdateByID generated by genieql
func DaemonUpdateByID(ctx context.Context, q sqlx.Queryer, id string, a Daemon) DaemonScannerStaticRow {
	const query = `UPDATE meta_daemons SET updated_at = NOW(), description = $2, hostname = $3 WHERE id = $1 RETURNING meta_daemons."created_at",meta_daemons."default",meta_daemons."description",meta_daemons."downloads",meta_daemons."hostname",meta_daemons."id",meta_daemons."updated_at"`
	var (
		c0 sql.NullString // id
		c1 sql.NullString // description
		c2 sql.NullString // hostname
	)
	c0.Valid = true
	c0.String = id
	c1.Valid = true
	c1.String = a.Description
	c2.Valid = true
	c2.String = a.Hostname
	return NewDaemonScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2))
}

// AuthzFindByBillingModify generated by genieql
func AuthzFindByBillingModify(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "billing_modify" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByBillingRead generated by genieql
func AuthzFindByBillingRead(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "billing_read" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByCommunityModify generated by genieql
func AuthzFindByCommunityModify(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "community_modify" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByCreatedAt generated by genieql
func AuthzFindByCreatedAt(ctx context.Context, q sqlx.Queryer, c ducktype.NullTime) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "created_at" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByID generated by genieql
func AuthzFindByID(ctx context.Context, q sqlx.Queryer, c sql.NullString) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "id" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByLibraryModify generated by genieql
func AuthzFindByLibraryModify(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "library_modify" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByLibraryRead generated by genieql
func AuthzFindByLibraryRead(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "library_read" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByProfileID generated by genieql
func AuthzFindByProfileID(ctx context.Context, q sqlx.Queryer, c sql.NullString) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "profile_id" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByUpdatedAt generated by genieql
func AuthzFindByUpdatedAt(ctx context.Context, q sqlx.Queryer, c ducktype.NullTime) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "updated_at" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzFindByUsermanagement generated by genieql
func AuthzFindByUsermanagement(ctx context.Context, q sqlx.Queryer, c sql.NullBool) AuthzScannerStaticRow {
	const query = `SELECT "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement" FROM "authz_meta" WHERE "usermanagement" = $1`
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// AuthzInsertWithDefaultsStaticColumns generated by genieql
const AuthzInsertWithDefaultsStaticColumns = `$1,$2,$3,DEFAULT,DEFAULT,$4,$5,$6,$7,$8`

// AuthzInsertWithDefaultsExplode generated by genieql
func AuthzInsertWithDefaultsExplode(a *Authz) ([]interface{}, error) {
	var (
		c0 sql.NullBool      // billing_modify
		c1 sql.NullBool      // billing_read
		c2 sql.NullBool      // community_modify
		c3 sql.NullBool      // library_modify
		c4 sql.NullBool      // library_read
		c5 sql.NullString    // profile_id
		c6 ducktype.NullTime // updated_at
		c7 sql.NullBool      // usermanagement
	)

	c0.Valid = true
	c0.Bool = a.BillingModify

	c1.Valid = true
	c1.Bool = a.BillingRead

	c2.Valid = true
	c2.Bool = a.CommunityModify

	c3.Valid = true
	c3.Bool = a.LibraryModify

	c4.Valid = true
	c4.Bool = a.LibraryRead

	c5.Valid = true
	c5.String = a.ProfileID

	switch ts := a.UpdatedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c6.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c6.NegativeInfinity()
	default:
		c6.Status = ducktype.Present
		c6.Time = a.UpdatedAt
	}

	c7.Valid = true
	c7.Bool = a.Usermanagement

	return []interface{}{c0, c1, c2, c3, c4, c5, c6, c7}, nil
}

// AuthzInsertWithDefaults generated by genieql
func AuthzInsertWithDefaults(ctx context.Context, q sqlx.Queryer, a Authz) AuthzScannerStaticRow {
	const query = `INSERT INTO "authz_meta" ("billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement") VALUES ($1,$2,$3,DEFAULT,DEFAULT,$4,$5,$6,$7,$8) RETURNING "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement"`
	var (
		c0 sql.NullBool      // billing_modify
		c1 sql.NullBool      // billing_read
		c2 sql.NullBool      // community_modify
		c3 sql.NullBool      // library_modify
		c4 sql.NullBool      // library_read
		c5 sql.NullString    // profile_id
		c6 ducktype.NullTime // updated_at
		c7 sql.NullBool
	)
	c0.Valid = true
	c0.Bool = a.BillingModify
	c1.Valid = true
	c1.Bool = a.BillingRead
	c2.Valid = true
	c2.Bool = a.CommunityModify
	c3.Valid = true
	c3.Bool = a.LibraryModify
	c4.Valid = true
	c4.Bool = a.LibraryRead
	c5.Valid = true
	c5.String = a.ProfileID
	switch ts := a.UpdatedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c6.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c6.NegativeInfinity()
	default:
		c6.Status = ducktype.Present
		c6.Time = a.UpdatedAt
	}
	c7.Valid = true
	c7.Bool = a.Usermanagement // usermanagement
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4, c5, c6, c7))
}

// AuthzInsertWithIDDefaultsStaticColumns generated by genieql
const AuthzInsertWithIDDefaultsStaticColumns = `$1,$2,$3,DEFAULT,$4,$5,$6,$7,$8,$9`

// AuthzInsertWithIDDefaultsExplode generated by genieql
func AuthzInsertWithIDDefaultsExplode(a *Authz) ([]interface{}, error) {
	var (
		c0 sql.NullBool      // billing_modify
		c1 sql.NullBool      // billing_read
		c2 sql.NullBool      // community_modify
		c3 sql.NullString    // id
		c4 sql.NullBool      // library_modify
		c5 sql.NullBool      // library_read
		c6 sql.NullString    // profile_id
		c7 ducktype.NullTime // updated_at
		c8 sql.NullBool      // usermanagement
	)

	c0.Valid = true
	c0.Bool = a.BillingModify

	c1.Valid = true
	c1.Bool = a.BillingRead

	c2.Valid = true
	c2.Bool = a.CommunityModify

	c3.Valid = true
	c3.String = a.ID

	c4.Valid = true
	c4.Bool = a.LibraryModify

	c5.Valid = true
	c5.Bool = a.LibraryRead

	c6.Valid = true
	c6.String = a.ProfileID

	switch ts := a.UpdatedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c7.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c7.NegativeInfinity()
	default:
		c7.Status = ducktype.Present
		c7.Time = a.UpdatedAt
	}

	c8.Valid = true
	c8.Bool = a.Usermanagement

	return []interface{}{c0, c1, c2, c3, c4, c5, c6, c7, c8}, nil
}

// AuthzInsertWithIDDefaults generated by genieql
func AuthzInsertWithIDDefaults(ctx context.Context, q sqlx.Queryer, a Authz) AuthzScannerStaticRow {
	const query = `INSERT INTO "authz_meta" ("billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement") VALUES ($1,$2,$3,DEFAULT,$4,$5,$6,$7,$8,$9) ON CONFLICT (id) DO UPDATE SET updated_at = DEFAULT RETURNING "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement"`
	var (
		c0 sql.NullBool      // billing_modify
		c1 sql.NullBool      // billing_read
		c2 sql.NullBool      // community_modify
		c3 sql.NullString    // id
		c4 sql.NullBool      // library_modify
		c5 sql.NullBool      // library_read
		c6 sql.NullString    // profile_id
		c7 ducktype.NullTime // updated_at
		c8 sql.NullBool
	)
	c0.Valid = true
	c0.Bool = a.BillingModify
	c1.Valid = true
	c1.Bool = a.BillingRead
	c2.Valid = true
	c2.Bool = a.CommunityModify
	c3.Valid = true
	c3.String = a.ID
	c4.Valid = true
	c4.Bool = a.LibraryModify
	c5.Valid = true
	c5.Bool = a.LibraryRead
	c6.Valid = true
	c6.String = a.ProfileID
	switch ts := a.UpdatedAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c7.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c7.NegativeInfinity()
	default:
		c7.Status = ducktype.Present
		c7.Time = a.UpdatedAt
	}
	c8.Valid = true
	c8.Bool = a.Usermanagement // usermanagement
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4, c5, c6, c7, c8))
}

// AuthzUpsertWithDefaultsStaticColumns generated by genieql
const AuthzUpsertWithDefaultsStaticColumns = `$1,$2,$3,DEFAULT,DEFAULT,$4,$5,$6,DEFAULT,$7`

// AuthzUpsertWithDefaultsExplode generated by genieql
func AuthzUpsertWithDefaultsExplode(p *Authz) ([]interface{}, error) {
	var (
		c0 sql.NullBool   // billing_modify
		c1 sql.NullBool   // billing_read
		c2 sql.NullBool   // community_modify
		c3 sql.NullBool   // library_modify
		c4 sql.NullBool   // library_read
		c5 sql.NullString // profile_id
		c6 sql.NullBool   // usermanagement
	)

	c0.Valid = true
	c0.Bool = p.BillingModify

	c1.Valid = true
	c1.Bool = p.BillingRead

	c2.Valid = true
	c2.Bool = p.CommunityModify

	c3.Valid = true
	c3.Bool = p.LibraryModify

	c4.Valid = true
	c4.Bool = p.LibraryRead

	c5.Valid = true
	c5.String = p.ProfileID

	c6.Valid = true
	c6.Bool = p.Usermanagement

	return []interface{}{c0, c1, c2, c3, c4, c5, c6}, nil
}

// AuthzUpsertWithDefaults generated by genieql
// upsert a single record with default fields.
func AuthzUpsertWithDefaults(ctx context.Context, q sqlx.Queryer, p Authz) AuthzScannerStaticRow {
	const query = `INSERT INTO "authz_meta" ("billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement") VALUES ($1,$2,$3,DEFAULT,DEFAULT,$4,$5,$6,DEFAULT,$7) ON CONFLICT (profile_id) DO UPDATE SET usermanagement = EXCLUDED.usermanagement, billing_read = EXCLUDED.billing_read, billing_modify = EXCLUDED.billing_modify, community_modify = EXCLUDED.community_modify, library_read = EXCLUDED.library_read, library_modify = EXCLUDED.library_modify, updated_at = DEFAULT RETURNING "billing_modify","billing_read","community_modify","created_at","id","library_modify","library_read","profile_id","updated_at","usermanagement"`
	var (
		c0 sql.NullBool   // billing_modify
		c1 sql.NullBool   // billing_read
		c2 sql.NullBool   // community_modify
		c3 sql.NullBool   // library_modify
		c4 sql.NullBool   // library_read
		c5 sql.NullString // profile_id
		c6 sql.NullBool
	)
	c0.Valid = true
	c0.Bool = p.BillingModify
	c1.Valid = true
	c1.Bool = p.BillingRead
	c2.Valid = true
	c2.Bool = p.CommunityModify
	c3.Valid = true
	c3.Bool = p.LibraryModify
	c4.Valid = true
	c4.Bool = p.LibraryRead
	c5.Valid = true
	c5.String = p.ProfileID
	c6.Valid = true
	c6.Bool = p.Usermanagement // usermanagement
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4, c5, c6))
}

// AuthzDeleteByProfileID generated by genieql
func AuthzDeleteByProfileID(ctx context.Context, q sqlx.Queryer, id string) AuthzScannerStaticRow {
	const query = `DELETE FROM authz_meta WHERE profile_id = $1 RETURNING authz_meta."billing_modify",authz_meta."billing_read",authz_meta."community_modify",authz_meta."created_at",authz_meta."id",authz_meta."library_modify",authz_meta."library_read",authz_meta."profile_id",authz_meta."updated_at",authz_meta."usermanagement"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewAuthzScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// ProfileFindByID generated by genieql
func ProfileFindByID(ctx context.Context, q sqlx.Queryer, id string) ProfileScannerStaticRow {
	const query = `SELECT meta_profiles."created_at",meta_profiles."disabled_at",meta_profiles."disabled_manually_at",meta_profiles."disabled_pending_approval_at",meta_profiles."display",meta_profiles."id",meta_profiles."session_watermark",meta_profiles."updated_at" FROM meta_profiles WHERE "id" = $1`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// ProfileUpdate generated by genieql
func ProfileUpdate(ctx context.Context, q sqlx.Queryer, p Profile) ProfileScannerStaticRow {
	const query = `UPDATE meta_profiles SET updated_at = NOW(), disabled_at = $1, disabled_manually_at = $2, disabled_pending_approval_at = $3, display = $4 WHERE id = $5 RETURNING meta_profiles."created_at",meta_profiles."disabled_at",meta_profiles."disabled_manually_at",meta_profiles."disabled_pending_approval_at",meta_profiles."display",meta_profiles."id",meta_profiles."session_watermark",meta_profiles."updated_at"`
	var (
		c0 ducktype.NullTime // disabled_at
		c1 ducktype.NullTime // disabled_manually_at
		c2 ducktype.NullTime // disabled_pending_approval_at
		c3 sql.NullString    // display
		c4 sql.NullString    // id
	)
	switch ts := p.DisabledAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c0.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c0.NegativeInfinity()
	default:
		c0.Status = ducktype.Present
		c0.Time = p.DisabledAt
	}
	switch ts := p.DisabledManuallyAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c1.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c1.NegativeInfinity()
	default:
		c1.Status = ducktype.Present
		c1.Time = p.DisabledManuallyAt
	}
	switch ts := p.DisabledPendingApprovalAt; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c2.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c2.NegativeInfinity()
	default:
		c2.Status = ducktype.Present
		c2.Time = p.DisabledPendingApprovalAt
	}
	c3.Valid = true
	c3.String = p.Display
	c4.Valid = true
	c4.String = p.ID
	return NewProfileScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4))
}

// WireguardFindByID generated by genieql
func WireguardFindByID(ctx context.Context, q sqlx.Queryer, id string) WireguardScannerStaticRow {
	const query = `SELECT meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at" FROM meta_wireguard WHERE id = $1`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// WireguardInsertWithDefaultsStaticColumns generated by genieql
const WireguardInsertWithDefaultsStaticColumns = `DEFAULT,$1,$2,$3,$4,$5,DEFAULT`

// WireguardInsertWithDefaultsExplode generated by genieql
func WireguardInsertWithDefaultsExplode(a *Wireguard) ([]interface{}, error) {
	var (
		c0 sql.NullBool   // default
		c1 sql.NullString // description
		c2 sql.NullInt64  // dns_rate_limit
		c3 sql.NullString // id
		c4 sql.NullInt32  // port
	)

	c0.Valid = true
	c0.Bool = a.Default

	c1.Valid = true
	c1.String = a.Description

	c2.Valid = true
	c2.Int64 = int64(a.DNSRateLimit)

	c3.Valid = true
	c3.String = a.ID

	c4.Valid = true
	c4.Int32 = int32(a.Port)

	return []interface{}{c0, c1, c2, c3, c4}, nil
}

// WireguardInsertWithDefaults generated by genieql
func WireguardInsertWithDefaults(ctx context.Context, q sqlx.Queryer, a Wireguard) WireguardScannerStaticRow {
	const query = `INSERT INTO "meta_wireguard" ("created_at","default","description","dns_rate_limit","id","port","updated_at") VALUES (DEFAULT,$1,$2,$3,$4,$5,DEFAULT) RETURNING "created_at","default","description","dns_rate_limit","id","port","updated_at"`
	var (
		c0 sql.NullBool   // default
		c1 sql.NullString // description
		c2 sql.NullInt64  // dns_rate_limit
		c3 sql.NullString // id
		c4 sql.NullInt32
	)
	c0.Valid = true
	c0.Bool = a.Default
	c1.Valid = true
	c1.String = a.Description
	c2.Valid = true
	c2.Int64 = int64(a.DNSRateLimit)
	c3.Valid = true
	c3.String = a.ID
	c4.Valid = true
	c4.Int32 = int32(a.Port) // port
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4))
}

// WireguardDeleteByID generated by genieql
func WireguardDeleteByID(ctx context.Context, q sqlx.Queryer, id string) WireguardScannerStaticRow {
	const query = `DELETE FROM meta_wireguard WHERE id = $1 RETURNING meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// WireguardCurrent generated by genieql
func WireguardCurrent(ctx context.Context, q sqlx.Queryer) WireguardScannerStaticRow {
	const query = `SELECT meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at" FROM meta_wireguard WHERE "default" LIMIT 1`
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query))
}

// WireguardTouch generated by genieql
func WireguardTouch(ctx context.Context, q sqlx.Queryer, id string) WireguardScannerStaticRow {
	const query = `UPDATE meta_wireguard SET "default" = (id = $1) WHERE "default" OR id = $1 RETURNING meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at"`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// WireguardUpdate generated by genieql
func WireguardUpdate(ctx context.Context, q sqlx.Queryer, a Wireguard) WireguardScannerStaticRow {
	const query = `UPDATE meta_wireguard SET description = $1, port = $4, dns_rate_limit = $2 WHERE id = $3 RETURNING meta_wireguard."created_at",meta_wireguard."default",meta_wireguard."description",meta_wireguard."dns_rate_limit",meta_wireguard."id",meta_wireguard."port",meta_wireguard."updated_at"`
	var (
		c0 sql.NullString // description
		c1 sql.NullInt64  // dns_rate_limit
		c2 sql.NullString // id
		c3 sql.NullInt32  // port
	)
	c0.Valid = true
	c0.String = a.Description
	c1.Valid = true
	c1.Int64 = int64(a.DNSRateLimit)
	c2.Valid = true
	c2.String = a.ID
	c3.Valid = true
	c3.Int32 = int32(a.Port)
	return NewWireguardScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3))
}
