FROM retrovibe.ubuntu:latest

# install android sdk

RUN sh /usr/share/eg/install/google-cloud.sh
RUN apt-get update && apt-get install -y openjdk-17-jdk curl unzip google-cloud-cli

RUN mkdir -p /opt/android-sdk/cmdline-tools && chown -R egd:egd /opt/android-sdk
RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o /tmp/tools.zip
RUN sudo -u egd unzip /tmp/tools.zip -d /tmp
RUN yes | sudo -u egd /tmp/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk "cmdline-tools;latest"
RUN yes | sudo -u egd /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk \
    "ndk;27.0.12077973" \
    "ndk;28.2.13676358" \
    "build-tools;35.0.0" \
    "build-tools;36.0.0" \
    "platforms;android-34" \
    "platforms;android-35" \
    "platforms;android-36" \
    "cmake;3.22.1" \
    "platform-tools"

RUN systemd-tmpfiles --create
RUN systemd-tmpfiles --clean
