syntax = "proto3";

package media;

import "meta/meta.search.proto";

message Known {
  string id = 1 [ json_name = "id" ];
  float rating = 2 [ json_name = "rating" ];
  bool adult = 3 [ json_name = "adult" ];
  string description = 4 [ json_name = "description" ];
  string summary = 5 [ json_name = "summary" ];
  string image = 6 [ json_name = "image" ];
  string released = 7 [ json_name = "released" ];
  string mimetype = 8 [ json_name = "mimetype" ];
  string source = 9 [ json_name = "source" ];
  string uid = 10 [ json_name = "uid" ];
}

message KnownSearchRequest {
  string query = 1 [ json_name = "query" ];
  bool adult = 2 [ json_name = "adult" ];
  string language = 3 [ json_name = "language" ];
  string mimetype = 4 [ json_name = "mimetype" ];
  meta.DateRange released = 5 [ json_name = "released" ];
  repeated string source = 6 [ json_name = "source" ];
  repeated string id = 7 [ json_name = "id" ];
  reserved 8 to 899;
  uint64 offset = 900 [ json_name = "offset" ];
  uint64 limit = 901 [ json_name = "limit" ];
  reserved 902 to 999;
}

message KnownSearchResponse {
  KnownSearchRequest next = 1 [ json_name = "next" ];
  repeated Known items = 2 [ json_name = "items" ];
}

message KnownMatchRequest { string query = 1 [ json_name = "query" ]; }

message KnownLookupRequest {}
message KnownLookupResponse { Known known = 1 [ json_name = "known" ]; }

message KnownDownloadRequest {}
message KnownDownloadResponse { Known known = 1 [ json_name = "known" ]; }

message KnownCreateRequest { Known known = 1 [ json_name = "known" ]; }
message KnownCreateResponse { Known known = 1 [ json_name = "known" ]; }

message KnownLatestRequest {
  meta.DateRange released = 1 [ json_name = "released" ];
  bool adult = 2 [ json_name = "adult" ];
  string language = 3 [ json_name = "language" ];
  string mimetype = 4 [ json_name = "mimetype" ];
  repeated string source = 5 [ json_name = "source" ];
  repeated string id = 6 [ json_name = "id" ];
  reserved 7 to 899;
  uint64 offset = 900 [ json_name = "offset" ];
  uint64 limit = 901 [ json_name = "limit" ];
  reserved 902 to 999;
}

message KnownLatestResponse {
  KnownLatestRequest next = 1 [ json_name = "next" ];
  repeated Known items = 2 [ json_name = "items" ];
}

message RecommendationSearchRequest {
  string mimetype = 1 [ json_name = "mimetype" ];
  bool adult = 2 [ json_name = "adult" ];
  string language = 3 [ json_name = "language" ];
  reserved 4 to 899;
  uint64 offset = 900 [ json_name = "offset" ];
  uint64 limit = 901 [ json_name = "limit" ];
  reserved 902 to 999;
}

message RecommendationSearchResponse {
  RecommendationSearchRequest next = 1 [ json_name = "next" ];
  repeated Known items = 2 [ json_name = "items" ];
}

message RecommendationFindRequest {}
message RecommendationFindResponse {
  Known recommendation = 1 [ json_name = "recomendation" ];
}

message RecommendationDeleteRequest {}
message RecommendationDeleteResponse {
  Known recommendation = 1 [ json_name = "recomendation" ];
}

message RecommendationRefreshRequest {
  string profile_id = 1 [ json_name = "profile_id" ];
  uint64 limit = 2 [ json_name = "limit" ];
  string mimetype = 3 [ json_name = "mimetype" ];
  bool adult = 4 [ json_name = "adult" ];
  string language = 5 [ json_name = "language" ];
}
message RecommendationRefreshResponse {}
