// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: media.recent.proto

package media

import (
	meta "github.com/retrovibed/retrovibed/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecentSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       *meta.DateRange        `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentSearchRequest) Reset() {
	*x = RecentSearchRequest{}
	mi := &file_media_recent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentSearchRequest) ProtoMessage() {}

func (x *RecentSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentSearchRequest.ProtoReflect.Descriptor instead.
func (*RecentSearchRequest) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{0}
}

func (x *RecentSearchRequest) GetCreated() *meta.DateRange {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *RecentSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RecentSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *RecentSearchRequest   `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*RecentRecordRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentSearchResponse) Reset() {
	*x = RecentSearchResponse{}
	mi := &file_media_recent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentSearchResponse) ProtoMessage() {}

func (x *RecentSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentSearchResponse.ProtoReflect.Descriptor instead.
func (*RecentSearchResponse) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{1}
}

func (x *RecentSearchResponse) GetNext() *RecentSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *RecentSearchResponse) GetItems() []*RecentRecordRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type RecentRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Media         *Media                 `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Duration      uint64                 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Position      uint64                 `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Query         *MediaSearchRequest    `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentRecordRequest) Reset() {
	*x = RecentRecordRequest{}
	mi := &file_media_recent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentRecordRequest) ProtoMessage() {}

func (x *RecentRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentRecordRequest.ProtoReflect.Descriptor instead.
func (*RecentRecordRequest) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{2}
}

func (x *RecentRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecentRecordRequest) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *RecentRecordRequest) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecentRecordRequest) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RecentRecordRequest) GetQuery() *MediaSearchRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type RecentRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentRecordResponse) Reset() {
	*x = RecentRecordResponse{}
	mi := &file_media_recent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentRecordResponse) ProtoMessage() {}

func (x *RecentRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentRecordResponse.ProtoReflect.Descriptor instead.
func (*RecentRecordResponse) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{3}
}

type RecentDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentDeleteRequest) Reset() {
	*x = RecentDeleteRequest{}
	mi := &file_media_recent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentDeleteRequest) ProtoMessage() {}

func (x *RecentDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentDeleteRequest.ProtoReflect.Descriptor instead.
func (*RecentDeleteRequest) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{4}
}

type RecentDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentDeleteResponse) Reset() {
	*x = RecentDeleteResponse{}
	mi := &file_media_recent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentDeleteResponse) ProtoMessage() {}

func (x *RecentDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_recent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentDeleteResponse.ProtoReflect.Descriptor instead.
func (*RecentDeleteResponse) Descriptor() ([]byte, []int) {
	return file_media_recent_proto_rawDescGZIP(), []int{5}
}

var File_media_recent_proto protoreflect.FileDescriptor

const file_media_recent_proto_rawDesc = "" +
	"\n" +
	"\x12media.recent.proto\x12\x05media\x1a\vmedia.proto\x1a\x11meta.search.proto\"\x7f\n" +
	"\x13RecentSearchRequest\x12)\n" +
	"\acreated\x18\x01 \x01(\v2\x0f.meta.DateRangeR\acreated\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x02\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"x\n" +
	"\x14RecentSearchResponse\x12.\n" +
	"\x04next\x18\x01 \x01(\v2\x1a.media.RecentSearchRequestR\x04next\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.media.RecentRecordRequestR\x05items\"\xb2\x01\n" +
	"\x13RecentRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x05media\x18\x02 \x01(\v2\f.media.MediaR\x05media\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x04R\bduration\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x04R\bposition\x12/\n" +
	"\x05query\x18\x05 \x01(\v2\x19.media.MediaSearchRequestR\x05query\"\x16\n" +
	"\x14RecentRecordResponse\"\x15\n" +
	"\x13RecentDeleteRequest\"\x16\n" +
	"\x14RecentDeleteResponseb\x06proto3"

var (
	file_media_recent_proto_rawDescOnce sync.Once
	file_media_recent_proto_rawDescData []byte
)

func file_media_recent_proto_rawDescGZIP() []byte {
	file_media_recent_proto_rawDescOnce.Do(func() {
		file_media_recent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_recent_proto_rawDesc), len(file_media_recent_proto_rawDesc)))
	})
	return file_media_recent_proto_rawDescData
}

var file_media_recent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_media_recent_proto_goTypes = []any{
	(*RecentSearchRequest)(nil),  // 0: media.RecentSearchRequest
	(*RecentSearchResponse)(nil), // 1: media.RecentSearchResponse
	(*RecentRecordRequest)(nil),  // 2: media.RecentRecordRequest
	(*RecentRecordResponse)(nil), // 3: media.RecentRecordResponse
	(*RecentDeleteRequest)(nil),  // 4: media.RecentDeleteRequest
	(*RecentDeleteResponse)(nil), // 5: media.RecentDeleteResponse
	(*meta.DateRange)(nil),       // 6: meta.DateRange
	(*Media)(nil),                // 7: media.Media
	(*MediaSearchRequest)(nil),   // 8: media.MediaSearchRequest
}
var file_media_recent_proto_depIdxs = []int32{
	6, // 0: media.RecentSearchRequest.created:type_name -> meta.DateRange
	0, // 1: media.RecentSearchResponse.next:type_name -> media.RecentSearchRequest
	2, // 2: media.RecentSearchResponse.items:type_name -> media.RecentRecordRequest
	7, // 3: media.RecentRecordRequest.media:type_name -> media.Media
	8, // 4: media.RecentRecordRequest.query:type_name -> media.MediaSearchRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_media_recent_proto_init() }
func file_media_recent_proto_init() {
	if File_media_recent_proto != nil {
		return
	}
	file_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_recent_proto_rawDesc), len(file_media_recent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_recent_proto_goTypes,
		DependencyIndexes: file_media_recent_proto_depIdxs,
		MessageInfos:      file_media_recent_proto_msgTypes,
	}.Build()
	File_media_recent_proto = out.File
	file_media_recent_proto_goTypes = nil
	file_media_recent_proto_depIdxs = nil
}
