// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: media.known.proto

package media

import (
	meta "github.com/retrovibed/retrovibed/shallows/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Known struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        float32                `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Adult         bool                   `protobuf:"varint,3,opt,name=adult,proto3" json:"adult,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Released      string                 `protobuf:"bytes,7,opt,name=released,proto3" json:"released,omitempty"`
	Mimetype      string                 `protobuf:"bytes,8,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Known) Reset() {
	*x = Known{}
	mi := &file_media_known_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Known) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Known) ProtoMessage() {}

func (x *Known) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Known.ProtoReflect.Descriptor instead.
func (*Known) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{0}
}

func (x *Known) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Known) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Known) GetAdult() bool {
	if x != nil {
		return x.Adult
	}
	return false
}

func (x *Known) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Known) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Known) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Known) GetReleased() string {
	if x != nil {
		return x.Released
	}
	return ""
}

func (x *Known) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

type KnownSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Adult         bool                   `protobuf:"varint,2,opt,name=adult,proto3" json:"adult,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Mimetype      string                 `protobuf:"bytes,4,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownSearchRequest) Reset() {
	*x = KnownSearchRequest{}
	mi := &file_media_known_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownSearchRequest) ProtoMessage() {}

func (x *KnownSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownSearchRequest.ProtoReflect.Descriptor instead.
func (*KnownSearchRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{1}
}

func (x *KnownSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *KnownSearchRequest) GetAdult() bool {
	if x != nil {
		return x.Adult
	}
	return false
}

func (x *KnownSearchRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *KnownSearchRequest) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *KnownSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KnownSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KnownSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *KnownSearchRequest    `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Known               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownSearchResponse) Reset() {
	*x = KnownSearchResponse{}
	mi := &file_media_known_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownSearchResponse) ProtoMessage() {}

func (x *KnownSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownSearchResponse.ProtoReflect.Descriptor instead.
func (*KnownSearchResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{2}
}

func (x *KnownSearchResponse) GetNext() *KnownSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *KnownSearchResponse) GetItems() []*Known {
	if x != nil {
		return x.Items
	}
	return nil
}

type KnownMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownMatchRequest) Reset() {
	*x = KnownMatchRequest{}
	mi := &file_media_known_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownMatchRequest) ProtoMessage() {}

func (x *KnownMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownMatchRequest.ProtoReflect.Descriptor instead.
func (*KnownMatchRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{3}
}

func (x *KnownMatchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type KnownLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLookupRequest) Reset() {
	*x = KnownLookupRequest{}
	mi := &file_media_known_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLookupRequest) ProtoMessage() {}

func (x *KnownLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLookupRequest.ProtoReflect.Descriptor instead.
func (*KnownLookupRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{4}
}

type KnownLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         *Known                 `protobuf:"bytes,1,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLookupResponse) Reset() {
	*x = KnownLookupResponse{}
	mi := &file_media_known_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLookupResponse) ProtoMessage() {}

func (x *KnownLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLookupResponse.ProtoReflect.Descriptor instead.
func (*KnownLookupResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{5}
}

func (x *KnownLookupResponse) GetKnown() *Known {
	if x != nil {
		return x.Known
	}
	return nil
}

type KnownDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownDownloadRequest) Reset() {
	*x = KnownDownloadRequest{}
	mi := &file_media_known_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownDownloadRequest) ProtoMessage() {}

func (x *KnownDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownDownloadRequest.ProtoReflect.Descriptor instead.
func (*KnownDownloadRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{6}
}

type KnownDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         *Known                 `protobuf:"bytes,1,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownDownloadResponse) Reset() {
	*x = KnownDownloadResponse{}
	mi := &file_media_known_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownDownloadResponse) ProtoMessage() {}

func (x *KnownDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownDownloadResponse.ProtoReflect.Descriptor instead.
func (*KnownDownloadResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{7}
}

func (x *KnownDownloadResponse) GetKnown() *Known {
	if x != nil {
		return x.Known
	}
	return nil
}

type KnownCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         *Known                 `protobuf:"bytes,1,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownCreateRequest) Reset() {
	*x = KnownCreateRequest{}
	mi := &file_media_known_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownCreateRequest) ProtoMessage() {}

func (x *KnownCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownCreateRequest.ProtoReflect.Descriptor instead.
func (*KnownCreateRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{8}
}

func (x *KnownCreateRequest) GetKnown() *Known {
	if x != nil {
		return x.Known
	}
	return nil
}

type KnownCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         *Known                 `protobuf:"bytes,1,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownCreateResponse) Reset() {
	*x = KnownCreateResponse{}
	mi := &file_media_known_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownCreateResponse) ProtoMessage() {}

func (x *KnownCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownCreateResponse.ProtoReflect.Descriptor instead.
func (*KnownCreateResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{9}
}

func (x *KnownCreateResponse) GetKnown() *Known {
	if x != nil {
		return x.Known
	}
	return nil
}

type KnownLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      *meta.DateRange        `protobuf:"bytes,1,opt,name=released,proto3" json:"released,omitempty"`
	Adult         bool                   `protobuf:"varint,2,opt,name=adult,proto3" json:"adult,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Mimetype      string                 `protobuf:"bytes,4,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLatestRequest) Reset() {
	*x = KnownLatestRequest{}
	mi := &file_media_known_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLatestRequest) ProtoMessage() {}

func (x *KnownLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLatestRequest.ProtoReflect.Descriptor instead.
func (*KnownLatestRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{10}
}

func (x *KnownLatestRequest) GetReleased() *meta.DateRange {
	if x != nil {
		return x.Released
	}
	return nil
}

func (x *KnownLatestRequest) GetAdult() bool {
	if x != nil {
		return x.Adult
	}
	return false
}

func (x *KnownLatestRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *KnownLatestRequest) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *KnownLatestRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KnownLatestRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KnownLatestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *KnownLatestRequest    `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Known               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLatestResponse) Reset() {
	*x = KnownLatestResponse{}
	mi := &file_media_known_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLatestResponse) ProtoMessage() {}

func (x *KnownLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLatestResponse.ProtoReflect.Descriptor instead.
func (*KnownLatestResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{11}
}

func (x *KnownLatestResponse) GetNext() *KnownLatestRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *KnownLatestResponse) GetItems() []*Known {
	if x != nil {
		return x.Items
	}
	return nil
}

type RecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mimetype      string                 `protobuf:"bytes,1,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Adult         bool                   `protobuf:"varint,2,opt,name=adult,proto3" json:"adult,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsRequest) Reset() {
	*x = RecommendationsRequest{}
	mi := &file_media_known_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequest) ProtoMessage() {}

func (x *RecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{12}
}

func (x *RecommendationsRequest) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *RecommendationsRequest) GetAdult() bool {
	if x != nil {
		return x.Adult
	}
	return false
}

func (x *RecommendationsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RecommendationsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RecommendationsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Next          *RecommendationsRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Known                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsResponse) Reset() {
	*x = RecommendationsResponse{}
	mi := &file_media_known_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse) ProtoMessage() {}

func (x *RecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{13}
}

func (x *RecommendationsResponse) GetNext() *RecommendationsRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *RecommendationsResponse) GetItems() []*Known {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_media_known_proto protoreflect.FileDescriptor

const file_media_known_proto_rawDesc = "" +
	"\n" +
	"\x11media.known.proto\x12\x05media\x1a\x11meta.search.proto\"\xcf\x01\n" +
	"\x05Known\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x02R\x06rating\x12\x14\n" +
	"\x05adult\x18\x03 \x01(\bR\x05adult\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x1a\n" +
	"\breleased\x18\a \x01(\tR\breleased\x12\x1a\n" +
	"\bmimetype\x18\b \x01(\tR\bmimetype\"\xb7\x01\n" +
	"\x12KnownSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05adult\x18\x02 \x01(\bR\x05adult\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bmimetype\x18\x04 \x01(\tR\bmimetype\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x05\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"h\n" +
	"\x13KnownSearchResponse\x12-\n" +
	"\x04next\x18\x01 \x01(\v2\x19.media.KnownSearchRequestR\x04next\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.media.KnownR\x05items\")\n" +
	"\x11KnownMatchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x14\n" +
	"\x12KnownLookupRequest\"9\n" +
	"\x13KnownLookupResponse\x12\"\n" +
	"\x05known\x18\x01 \x01(\v2\f.media.KnownR\x05known\"\x16\n" +
	"\x14KnownDownloadRequest\";\n" +
	"\x15KnownDownloadResponse\x12\"\n" +
	"\x05known\x18\x01 \x01(\v2\f.media.KnownR\x05known\"8\n" +
	"\x12KnownCreateRequest\x12\"\n" +
	"\x05known\x18\x01 \x01(\v2\f.media.KnownR\x05known\"9\n" +
	"\x13KnownCreateResponse\x12\"\n" +
	"\x05known\x18\x01 \x01(\v2\f.media.KnownR\x05known\"\xce\x01\n" +
	"\x12KnownLatestRequest\x12+\n" +
	"\breleased\x18\x01 \x01(\v2\x0f.meta.DateRangeR\breleased\x12\x14\n" +
	"\x05adult\x18\x02 \x01(\bR\x05adult\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bmimetype\x18\x04 \x01(\tR\bmimetype\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x05\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"h\n" +
	"\x13KnownLatestResponse\x12-\n" +
	"\x04next\x18\x01 \x01(\v2\x19.media.KnownLatestRequestR\x04next\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.media.KnownR\x05items\"\xa5\x01\n" +
	"\x16RecommendationsRequest\x12\x1a\n" +
	"\bmimetype\x18\x01 \x01(\tR\bmimetype\x12\x14\n" +
	"\x05adult\x18\x02 \x01(\bR\x05adult\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x04\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"p\n" +
	"\x17RecommendationsResponse\x121\n" +
	"\x04next\x18\x01 \x01(\v2\x1d.media.RecommendationsRequestR\x04next\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.media.KnownR\x05itemsb\x06proto3"

var (
	file_media_known_proto_rawDescOnce sync.Once
	file_media_known_proto_rawDescData []byte
)

func file_media_known_proto_rawDescGZIP() []byte {
	file_media_known_proto_rawDescOnce.Do(func() {
		file_media_known_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_known_proto_rawDesc), len(file_media_known_proto_rawDesc)))
	})
	return file_media_known_proto_rawDescData
}

var file_media_known_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_media_known_proto_goTypes = []any{
	(*Known)(nil),                   // 0: media.Known
	(*KnownSearchRequest)(nil),      // 1: media.KnownSearchRequest
	(*KnownSearchResponse)(nil),     // 2: media.KnownSearchResponse
	(*KnownMatchRequest)(nil),       // 3: media.KnownMatchRequest
	(*KnownLookupRequest)(nil),      // 4: media.KnownLookupRequest
	(*KnownLookupResponse)(nil),     // 5: media.KnownLookupResponse
	(*KnownDownloadRequest)(nil),    // 6: media.KnownDownloadRequest
	(*KnownDownloadResponse)(nil),   // 7: media.KnownDownloadResponse
	(*KnownCreateRequest)(nil),      // 8: media.KnownCreateRequest
	(*KnownCreateResponse)(nil),     // 9: media.KnownCreateResponse
	(*KnownLatestRequest)(nil),      // 10: media.KnownLatestRequest
	(*KnownLatestResponse)(nil),     // 11: media.KnownLatestResponse
	(*RecommendationsRequest)(nil),  // 12: media.RecommendationsRequest
	(*RecommendationsResponse)(nil), // 13: media.RecommendationsResponse
	(*meta.DateRange)(nil),          // 14: meta.DateRange
}
var file_media_known_proto_depIdxs = []int32{
	1,  // 0: media.KnownSearchResponse.next:type_name -> media.KnownSearchRequest
	0,  // 1: media.KnownSearchResponse.items:type_name -> media.Known
	0,  // 2: media.KnownLookupResponse.known:type_name -> media.Known
	0,  // 3: media.KnownDownloadResponse.known:type_name -> media.Known
	0,  // 4: media.KnownCreateRequest.known:type_name -> media.Known
	0,  // 5: media.KnownCreateResponse.known:type_name -> media.Known
	14, // 6: media.KnownLatestRequest.released:type_name -> meta.DateRange
	10, // 7: media.KnownLatestResponse.next:type_name -> media.KnownLatestRequest
	0,  // 8: media.KnownLatestResponse.items:type_name -> media.Known
	12, // 9: media.RecommendationsResponse.next:type_name -> media.RecommendationsRequest
	0,  // 10: media.RecommendationsResponse.items:type_name -> media.Known
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_media_known_proto_init() }
func file_media_known_proto_init() {
	if File_media_known_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_known_proto_rawDesc), len(file_media_known_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_known_proto_goTypes,
		DependencyIndexes: file_media_known_proto_depIdxs,
		MessageInfos:      file_media_known_proto_msgTypes,
	}.Build()
	File_media_known_proto = out.File
	file_media_known_proto_goTypes = nil
	file_media_known_proto_depIdxs = nil
}
