// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: media.remote.control.proto

package mediaapi

import (
	media "github.com/retrovibed/retrovibed/shallows/media"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enqueue a bit of media for playback.
type Queue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *media.Media           `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_media_remote_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_media_remote_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_media_remote_control_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetMedia() *media.Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// dequeue the media with the given id.
type Dequeue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dequeue) Reset() {
	*x = Dequeue{}
	mi := &file_media_remote_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dequeue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dequeue) ProtoMessage() {}

func (x *Dequeue) ProtoReflect() protoreflect.Message {
	mi := &file_media_remote_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dequeue.ProtoReflect.Descriptor instead.
func (*Dequeue) Descriptor() ([]byte, []int) {
	return file_media_remote_control_proto_rawDescGZIP(), []int{1}
}

func (x *Dequeue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// playpause commands the device to toggle media playback.
// the paused flag is to
type PlayPause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paused        bool                   `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPause) Reset() {
	*x = PlayPause{}
	mi := &file_media_remote_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPause) ProtoMessage() {}

func (x *PlayPause) ProtoReflect() protoreflect.Message {
	mi := &file_media_remote_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPause.ProtoReflect.Descriptor instead.
func (*PlayPause) Descriptor() ([]byte, []int) {
	return file_media_remote_control_proto_rawDescGZIP(), []int{2}
}

func (x *PlayPause) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

// Seek - move forward/back the given amount of time (millisecopnds)
type Seek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seek) Reset() {
	*x = Seek{}
	mi := &file_media_remote_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seek) ProtoMessage() {}

func (x *Seek) ProtoReflect() protoreflect.Message {
	mi := &file_media_remote_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seek.ProtoReflect.Descriptor instead.
func (*Seek) Descriptor() ([]byte, []int) {
	return file_media_remote_control_proto_rawDescGZIP(), []int{3}
}

func (x *Seek) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// represents a stream of commands / responses for the remote control.
// each command / response will contain a 'sid' representing the sequentialish
// id.
type Stream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Sid   string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Stream_Queue
	//	*Stream_Dequeue
	//	*Stream_Playpause
	//	*Stream_Seek
	Command       isStream_Command `protobuf_oneof:"Command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_media_remote_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_media_remote_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_media_remote_control_proto_rawDescGZIP(), []int{4}
}

func (x *Stream) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Stream) GetCommand() isStream_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Stream) GetQueue() *Queue {
	if x != nil {
		if x, ok := x.Command.(*Stream_Queue); ok {
			return x.Queue
		}
	}
	return nil
}

func (x *Stream) GetDequeue() *Dequeue {
	if x != nil {
		if x, ok := x.Command.(*Stream_Dequeue); ok {
			return x.Dequeue
		}
	}
	return nil
}

func (x *Stream) GetPlaypause() *PlayPause {
	if x != nil {
		if x, ok := x.Command.(*Stream_Playpause); ok {
			return x.Playpause
		}
	}
	return nil
}

func (x *Stream) GetSeek() *Seek {
	if x != nil {
		if x, ok := x.Command.(*Stream_Seek); ok {
			return x.Seek
		}
	}
	return nil
}

type isStream_Command interface {
	isStream_Command()
}

type Stream_Queue struct {
	Queue *Queue `protobuf:"bytes,1000,opt,name=queue,proto3,oneof"`
}

type Stream_Dequeue struct {
	Dequeue *Dequeue `protobuf:"bytes,1002,opt,name=dequeue,proto3,oneof"`
}

type Stream_Playpause struct {
	Playpause *PlayPause `protobuf:"bytes,1003,opt,name=playpause,proto3,oneof"`
}

type Stream_Seek struct {
	Seek *Seek `protobuf:"bytes,1004,opt,name=seek,proto3,oneof"`
}

func (*Stream_Queue) isStream_Command() {}

func (*Stream_Dequeue) isStream_Command() {}

func (*Stream_Playpause) isStream_Command() {}

func (*Stream_Seek) isStream_Command() {}

var File_media_remote_control_proto protoreflect.FileDescriptor

const file_media_remote_control_proto_rawDesc = "" +
	"\n" +
	"\x1amedia.remote.control.proto\x12\x05media\x1a\vmedia.proto\"+\n" +
	"\x05Queue\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\x19\n" +
	"\aDequeue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\tPlayPause\x12\x16\n" +
	"\x06paused\x18\x01 \x01(\bR\x06paused\"\x1e\n" +
	"\x04Seek\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\"\xd0\x01\n" +
	"\x06Stream\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12%\n" +
	"\x05queue\x18\xe8\a \x01(\v2\f.media.QueueH\x00R\x05queue\x12+\n" +
	"\adequeue\x18\xea\a \x01(\v2\x0e.media.DequeueH\x00R\adequeue\x121\n" +
	"\tplaypause\x18\xeb\a \x01(\v2\x10.media.PlayPauseH\x00R\tplaypause\x12\"\n" +
	"\x04seek\x18\xec\a \x01(\v2\v.media.SeekH\x00R\x04seekB\t\n" +
	"\aCommandb\x06proto3"

var (
	file_media_remote_control_proto_rawDescOnce sync.Once
	file_media_remote_control_proto_rawDescData []byte
)

func file_media_remote_control_proto_rawDescGZIP() []byte {
	file_media_remote_control_proto_rawDescOnce.Do(func() {
		file_media_remote_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_remote_control_proto_rawDesc), len(file_media_remote_control_proto_rawDesc)))
	})
	return file_media_remote_control_proto_rawDescData
}

var file_media_remote_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_media_remote_control_proto_goTypes = []any{
	(*Queue)(nil),       // 0: media.Queue
	(*Dequeue)(nil),     // 1: media.Dequeue
	(*PlayPause)(nil),   // 2: media.PlayPause
	(*Seek)(nil),        // 3: media.Seek
	(*Stream)(nil),      // 4: media.Stream
	(*media.Media)(nil), // 5: media.Media
}
var file_media_remote_control_proto_depIdxs = []int32{
	5, // 0: media.Queue.media:type_name -> media.Media
	0, // 1: media.Stream.queue:type_name -> media.Queue
	1, // 2: media.Stream.dequeue:type_name -> media.Dequeue
	2, // 3: media.Stream.playpause:type_name -> media.PlayPause
	3, // 4: media.Stream.seek:type_name -> media.Seek
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_media_remote_control_proto_init() }
func file_media_remote_control_proto_init() {
	if File_media_remote_control_proto != nil {
		return
	}
	file_media_remote_control_proto_msgTypes[4].OneofWrappers = []any{
		(*Stream_Queue)(nil),
		(*Stream_Dequeue)(nil),
		(*Stream_Playpause)(nil),
		(*Stream_Seek)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_remote_control_proto_rawDesc), len(file_media_remote_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_remote_control_proto_goTypes,
		DependencyIndexes: file_media_remote_control_proto_depIdxs,
		MessageInfos:      file_media_remote_control_proto_msgTypes,
	}.Build()
	File_media_remote_control_proto = out.File
	file_media_remote_control_proto_goTypes = nil
	file_media_remote_control_proto_depIdxs = nil
}
