syntax = "proto3";

package ddisc;

import "meta/meta.search.proto";

enum AcquisitionState {
  Unknown = 0;
  Ephemeral = 1;   // search result, not persisted.
  Available = 2;   // was persisted but download was not initaited. generally
                   // means it was put into the recommendations queue.
  Downloading = 3; // actively being downloaded.
  Completed = 4;   // we completed a download of this record.
}

message Discovery {
  string id = 1 [ json_name = "id" ];
  bytes infohash = 2 [ json_name = "infohash" ];
  uint32 attempts = 3 [ json_name = "attempts" ];
  string next_check = 4 [ json_name = "next_check" ];
  string created_at = 5 [ json_name = "created_at" ];
  string updated_at = 6 [ json_name = "updated_at" ];
  string title = 7 [ json_name = "title" ];
  string description = 8 [ json_name = "description" ];
  uint32 health = 9 [ json_name = "health" ];
  uint64 bytes = 10 [ json_name = "bytes" ];
  uint32 policy_rank = 11 [ json_name = "policy_rank" ];
  string known_media_id = 12 [ json_name = "known_media_id" ];
  string source = 13 [ json_name = "source" ];
  string uri = 14 [ json_name = "uri" ];
  AcquisitionState acquisition_state = 15 [ json_name = "acquisition_state" ];
}

message DiscoverySearchRequest {
  meta.DateRange next_check = 1 [ json_name = "next_check" ];
  repeated string id = 2 [ json_name = "id" ];
  uint64 attempts_min = 3 [ json_name = "attempts_min" ];
  uint64 attempts_max = 4 [ json_name = "attempts_max" ];
  reserved 5 to 999;
  uint64 offset = 1000 [ json_name = "offset" ];
  uint64 limit = 1001 [ json_name = "limit" ];
}

message DiscoverySearchResponse {
  DiscoverySearchRequest next = 1 [ json_name = "next" ];
  repeated Discovery items = 2 [ json_name = "items" ];
}

message DiscoveryCreateRequest {
  Discovery discovery = 1 [ json_name = "discovery" ];
}
message DiscoveryCreateResponse {
  Discovery discovery = 1 [ json_name = "discovery" ];
}

message DiscoveryDownloadRequest {
  Discovery discovery = 1 [ json_name = "discovery" ];
  bool autodownload = 2 [ json_name = "autodownload" ];
}
message DiscoveryDownloadResponse {
  Discovery discovery = 1 [ json_name = "discovery" ];
}

message DiscoveryDeleteRequest {}
message DiscoveryDeleteResponse {
  Discovery discovery = 1 [ json_name = "discovery" ];
}
