syntax = "proto3";

package meta;

message Bearer {
  // START OF STANDARD FIELDS
  string id = 1 [ json_name = "jti" ];
  string issuer = 2 [ json_name = "iss" ];
  string profile_id = 3 [ json_name = "sub" ];
  string session_id = 4 [ json_name = "sid" ];
  int64 issued = 5 [ json_name = "iat" ];
  int64 expires = 6 [ json_name = "exp" ];
  int64 not_before = 7 [ json_name = "nbf" ];
  // END OF STANDARD FIELDS
}

message Token {
  // START OF STANDARD FIELDS
  string id = 1 [ json_name = "jti" ];
  string issuer = 2 [ json_name = "iss" ];
  string profile_id = 3 [ json_name = "sub" ];
  string session_id = 4 [ json_name = "sid" ];
  int64 issued = 5 [ json_name = "iat" ];
  int64 expires = 6 [ json_name = "exp" ];
  int64 not_before = 7 [ json_name = "nbf" ];
  // END OF STANDARD FIELDS
  reserved 9 to 999;
  bool usermanagement = 1000 [ json_name = "usermanagement" ];
  bool remote_control = 1001 [ json_name = "remote_control" ];
  bool billing_read = 1002 [ json_name = "billing_read" ];
  bool billing_modify = 1003 [ json_name = "billing_modify" ];
  bool community_modify = 1004 [ json_name = "community_modify" ];
  uint64 archive_upload = 1005 [ json_name = "archive_upload" ];
  uint64 archive_download = 1006 [ json_name = "archive_download" ];
  bool library_read = 1007 [ json_name = "library_read" ];
  bool library_modify = 1008 [ json_name = "library_modify" ];
  bool archive_sync = 1009 [ json_name = "archive_sync" ];
  bool community_sync = 1010 [ json_name = "community_sync" ];
}

message AuthzRequest {}
message AuthzResponse {
  string bearer = 1 [ json_name = "bearer" ];
  Token token = 2 [ json_name = "token" ];
}

message AuthzGrantRequest { Token token = 1 [ json_name = "token" ]; }
message AuthzGrantResponse { Token token = 1 [ json_name = "token" ]; }

message AuthzRevokeRequest { Token token = 1 [ json_name = "token" ]; }
message AuthzRevokeResponse { Token token = 1 [ json_name = "token" ]; }

message AuthzProfileRequest {
  string profile_id = 1 [ json_name = "profile_id" ];
}
message AuthzProfileResponse { Token token = 1 [ json_name = "token" ]; }
