syntax = "proto3";

package meta;

message TorrentDiagnostics {
  uint64 total = 1 [ json_name = "total" ];
  uint64 seeding = 2 [ json_name = "seeding" ];
  uint64 bytes = 3 [ json_name = "bytes" ];
  uint64 downloaded = 4 [ json_name = "downloaded" ];
  uint64 uploaded = 5 [ json_name = "uploaded" ];
  uint64 peers = 6 [ json_name = "peers" ];
}

message TorrentMetricsResponse {
  TorrentDiagnostics torrent = 1 [ json_name = "torrent" ];
}

message TorrentInfoResponse {
  TorrentMeta meta = 1 [json_name = "meta"];
  TorrentDetails details = 2 [json_name = "details"];
  repeated TorrentFile files = 1000 [json_name = "files"];
}

message TorrentFile {
  string name = 1 [ json_name = "name" ];
  uint64 length = 2 [json_name = "length"];
  string path = 3 [ json_name = "path" ];
}

message TorrentMeta {
  string comment = 1 [ json_name = "comment" ];
  string encoding = 2 [ json_name = "encoding" ];
  string created_by = 3 [ json_name = "created_by" ];
  uint64 creation_date = 4 [json_name = "creation_date"];
  repeated string announce_list = 1000 [json_name = "announce_list"];
  repeated string url_list = 1001 [json_name = "url_list"];
}

message TorrentDetails {
  string name = 1 [ json_name = "name" ];
  uint64 length = 2 [json_name = "length"];
  string source = 3 [json_name = "source"];
  bool private = 4 [json_name = "private"];
}
