syntax = "proto3";

package retrovibed.community;

enum PublishMode {
  UNLISTED = 0;
  LISTED = 1;
  SYNDICATED = 2;
}

message Community {
  string id = 1 [ json_name = "id" ];
  string account_id = 2 [ json_name = "account_id" ];
  string created_at = 4 [ json_name = "created_at" ];
  string updated_at = 5 [ json_name = "updated_at" ];
  string mimetype = 6 [ json_name = "mimetype" ];
  reserved 7;
  string description = 8 [ json_name = "description" ];
  string entropy = 9 [ json_name = "entropy" ];
  uint64 bytes = 10 [ json_name = "bytes" ];
  string subscribed_at = 11 [ json_name = "subscribed_at" ];
  PublishMode default_publish_mode = 12 [ json_name = "default_publish_mode" ];
  bool hidden = 13 [ json_name = "hidden" ];
  string url = 14 [ json_name = "url" ];
  bool adult = 15 [ json_name = "adult" ];
  uint64 default_ttl = 16 [ json_name = "default_ttl" ];
  string default_language = 17 [ json_name = "default_language" ];
  reserved 18 to 999;
  // private fields for retrovibed use only, not populated by clients.
  string last_sync_at = 1000 [ json_name = "last_sync_at" ];
}

message CommunitySearchRequest {
  string query = 1 [ json_name = "query" ];
  uint64 offset = 2 [ json_name = "offset" ];
  uint64 limit = 3 [ json_name = "limit" ];
  reserved 4 to 999;
}

message CommunitySearchResponse {
  CommunitySearchRequest next = 1 [ json_name = "next" ];
  repeated Community items = 2 [ json_name = "items" ];
}

message CommunityCreateRequest {
  Community community = 1 [ json_name = "community" ];
}
message CommunityCreateResponse {
  Community community = 1 [ json_name = "community" ];
}

message CommunityFindRequest {}
message CommunityFindResponse {
  Community community = 1 [ json_name = "community" ];
}

message CommunityUploadRequest {
  Community community = 1 [ json_name = "community" ];
}
message CommunityUploadResponse {
  Community community = 1 [ json_name = "community" ];
}

message CommunityDeleteRequest {}
message CommunityDeleteResponse {
  Community community = 1 [ json_name = "community" ];
}

message CommunityUpdateRequest {
  Community community = 1 [ json_name = "community" ];
}
message CommunityUpdateResponse {
  Community community = 1 [ json_name = "community" ];
}

message CommunitySubscribeRequest {}
message CommunitySubscribeResponse {}

message YouTubeStatus {
  bool linked = 1 [ json_name = "linked" ];
  string id = 2 [ json_name = "id" ];
}
