# statically load the requested extensions
duckdb_extension_load(autocomplete)
duckdb_extension_load(json)
duckdb_extension_load(parquet)
duckdb_extension_load(icu)

set(BUILD_UNITTESTS 0 CACHE BOOL "Disable unit tests" FORCE)
set(BUILD_SHELL 0 CACHE BOOL "Disable CLI shell" FORCE)
set(ENABLE_EXTENSION_AUTOLOADING 1 CACHE BOOL "Enable extension autoloading" FORCE)
set(ENABLE_EXTENSION_AUTOINSTALL 1 CACHE BOOL "Enable extension autoinstall" FORCE)
set(EXTENSION_STATIC_BUILD 1 CACHE BOOL "Enable extension static build" FORCE)
set(CMAKE_VERBOSE_MAKEFILE on CACHE BOOL "Verbose build output" FORCE)
set(DUCKDB_EXTRA_LINK_FLAGS "-llog -Wl,-z,max-page-size=16384" CACHE STRING "Android extra link flags" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,-z,max-page-size=16384" CACHE STRING "Android shared linker flags" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-Wl,-z,max-page-size=16384" CACHE STRING "Android exe linker flags" FORCE)
