# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    await_only_futures: false
    camel_case_extensions: false
    camel_case_types: false
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    depend_on_referenced_packages: false
    empty_constructor_bodies: false
    no_leading_underscores_for_library_prefixes: false
    no_leading_underscores_for_local_identifiers: false
    no_logic_in_create_state: false
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_function_declarations_over_variables: false
    prefer_final_fields: false
    prefer_final_locals: false
    prefer_is_empty: false
    prefer_is_not_operator: false
    prefer_single_quotes: false
    prefer_typing_uninitialized_variables: false
    sort_child_properties_last: false
    sized_box_for_whitespace: false
    strict_top_level_inference: false
    type_init_formals: false
    unintended_html_in_doc_comment: false
    unnecessary_brace_in_string_interps: false
    unnecessary_const: false
    unnecessary_final: false
    unnecessary_getters_setters: false
    unnecessary_new: false
    unnecessary_nullable_for_final_variable_declarations: false
    unnecessary_this: false
    unnecessary_underscores: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    prefer_contains: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_foreach: false
    prefer_generic_function_type_aliases: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_if_null_operators: false
    prefer_initializing_formals: false
    prefer_inlined_adds: false
    prefer_interpolation_to_compose_strings: false
    prefer_is_not_empty: false
    prefer_iterable_whereType: false
    prefer_mixin: false
    prefer_null_aware_method_calls: false
    prefer_null_aware_operators: false
    prefer_spread_collections: false
    recursive_getters: false
    use_build_context_synchronously: false
    use_is_even_rather_than_modulo: false
    use_key_in_widget_constructors: false
    use_rethrow_when_possible: false
    use_super_parameters: false
    annotate_overrides: false
    avoid_init_to_null: false
    avoid_renaming_method_parameters: false
    avoid_single_cascade_in_expression_statements: false
    avoid_unnecessary_containers: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
formatter:
  page_width: 120
  trailing_commas: preserve
analyzer:
  exclude:
    - ".eg.cache/**"
  errors:
    library_private_types_in_public_api: ignore
