FROM ubuntu:resolute
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "cache buster 159a9a06-1686-4f49-9a7f-a30535706d59"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo podman netavark rsync vim dput devscripts dh-make dput git uidmap dbus-user-session tree python3 python3-venv cmake ccache ninja-build libssl-dev
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN apt-get update
RUN apt-get -y install golang-1.26 eg egbootstrap

RUN ln -s /usr/lib/go-1.26/bin/go /usr/local/bin/go

RUN systemd-sysusers
RUN systemd-tmpfiles --create

# hack due to ubuntu updating sudo
RUN update-alternatives --set sudo /usr/bin/sudo.ws
