// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ddisc/ddisc.import.proto

package ddiscapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Health        uint32                 `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Uritype       string                 `protobuf:"bytes,4,opt,name=uritype,proto3" json:"uritype,omitempty"`
	KnownMediaId  string                 `protobuf:"bytes,5,opt,name=known_media_id,proto3" json:"known_media_id,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Overview      string                 `protobuf:"bytes,7,opt,name=overview,proto3" json:"overview,omitempty"`
	Popularity    float64                `protobuf:"fixed64,8,opt,name=popularity,proto3" json:"popularity,omitempty"`
	PosterPath    string                 `protobuf:"bytes,9,opt,name=poster_path,proto3" json:"poster_path,omitempty"`
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Bytes         uint64                 `protobuf:"varint,11,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_ddisc_ddisc_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_ddisc_ddisc_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_ddisc_ddisc_import_proto_rawDescGZIP(), []int{0}
}

func (x *Import) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Import) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Import) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Import) GetUritype() string {
	if x != nil {
		return x.Uritype
	}
	return ""
}

func (x *Import) GetKnownMediaId() string {
	if x != nil {
		return x.KnownMediaId
	}
	return ""
}

func (x *Import) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Import) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *Import) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Import) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *Import) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Import) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

var File_ddisc_ddisc_import_proto protoreflect.FileDescriptor

const file_ddisc_ddisc_import_proto_rawDesc = "" +
	"\n" +
	"\x18ddisc/ddisc.import.proto\x12\x05ddisc\"\xb2\x02\n" +
	"\x06Import\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x16\n" +
	"\x06health\x18\x02 \x01(\rR\x06health\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x18\n" +
	"\auritype\x18\x04 \x01(\tR\auritype\x12&\n" +
	"\x0eknown_media_id\x18\x05 \x01(\tR\x0eknown_media_id\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1a\n" +
	"\boverview\x18\a \x01(\tR\boverview\x12\x1e\n" +
	"\n" +
	"popularity\x18\b \x01(\x01R\n" +
	"popularity\x12 \n" +
	"\vposter_path\x18\t \x01(\tR\vposter_path\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x14\n" +
	"\x05bytes\x18\v \x01(\x04R\x05bytesb\x06proto3"

var (
	file_ddisc_ddisc_import_proto_rawDescOnce sync.Once
	file_ddisc_ddisc_import_proto_rawDescData []byte
)

func file_ddisc_ddisc_import_proto_rawDescGZIP() []byte {
	file_ddisc_ddisc_import_proto_rawDescOnce.Do(func() {
		file_ddisc_ddisc_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ddisc_ddisc_import_proto_rawDesc), len(file_ddisc_ddisc_import_proto_rawDesc)))
	})
	return file_ddisc_ddisc_import_proto_rawDescData
}

var file_ddisc_ddisc_import_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ddisc_ddisc_import_proto_goTypes = []any{
	(*Import)(nil), // 0: ddisc.Import
}
var file_ddisc_ddisc_import_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ddisc_ddisc_import_proto_init() }
func file_ddisc_ddisc_import_proto_init() {
	if File_ddisc_ddisc_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ddisc_ddisc_import_proto_rawDesc), len(file_ddisc_ddisc_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddisc_ddisc_import_proto_goTypes,
		DependencyIndexes: file_ddisc_ddisc_import_proto_depIdxs,
		MessageInfos:      file_ddisc_ddisc_import_proto_msgTypes,
	}.Build()
	File_ddisc_ddisc_import_proto = out.File
	file_ddisc_ddisc_import_proto_goTypes = nil
	file_ddisc_ddisc_import_proto_depIdxs = nil
}
