// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: community/community.publish.proto

package communityapi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishedContent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommunityId    string                 `protobuf:"bytes,2,opt,name=community_id,proto3" json:"community_id,omitempty"`
	KnownMediaId   string                 `protobuf:"bytes,3,opt,name=known_media_id,proto3" json:"known_media_id,omitempty"`
	MagnetUri      string                 `protobuf:"bytes,4,opt,name=magnet_uri,proto3" json:"magnet_uri,omitempty"`
	PublishedAt    string                 `protobuf:"bytes,5,opt,name=published_at,proto3" json:"published_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	ArchivedId     string                 `protobuf:"bytes,8,opt,name=archived_id,proto3" json:"archived_id,omitempty"`
	Title          string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Mimetype       string                 `protobuf:"bytes,11,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	EncryptionSeed string                 `protobuf:"bytes,12,opt,name=encryption_seed,proto3" json:"encryption_seed,omitempty"`
	Bytes          uint64                 `protobuf:"varint,13,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// private fields for retrovibed use only, not populated by clients.
	LibraryId     string `protobuf:"bytes,1000,opt,name=library_id,proto3" json:"library_id,omitempty"`
	OauthGoogleId string `protobuf:"bytes,1001,opt,name=oauth_google_id,proto3" json:"oauth_google_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedContent) Reset() {
	*x = PublishedContent{}
	mi := &file_community_community_publish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedContent) ProtoMessage() {}

func (x *PublishedContent) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedContent.ProtoReflect.Descriptor instead.
func (*PublishedContent) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishedContent) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *PublishedContent) GetKnownMediaId() string {
	if x != nil {
		return x.KnownMediaId
	}
	return ""
}

func (x *PublishedContent) GetMagnetUri() string {
	if x != nil {
		return x.MagnetUri
	}
	return ""
}

func (x *PublishedContent) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *PublishedContent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PublishedContent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PublishedContent) GetArchivedId() string {
	if x != nil {
		return x.ArchivedId
	}
	return ""
}

func (x *PublishedContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishedContent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishedContent) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *PublishedContent) GetEncryptionSeed() string {
	if x != nil {
		return x.EncryptionSeed
	}
	return ""
}

func (x *PublishedContent) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *PublishedContent) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *PublishedContent) GetOauthGoogleId() string {
	if x != nil {
		return x.OauthGoogleId
	}
	return ""
}

type PublishContentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublishedContent *PublishedContent      `protobuf:"bytes,1,opt,name=published_content,proto3" json:"published_content,omitempty"`
	PublishMode      PublishMode            `protobuf:"varint,2,opt,name=publish_mode,proto3,enum=retrovibed.community.PublishMode" json:"publish_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishContentRequest) Reset() {
	*x = PublishContentRequest{}
	mi := &file_community_community_publish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentRequest) ProtoMessage() {}

func (x *PublishContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentRequest.ProtoReflect.Descriptor instead.
func (*PublishContentRequest) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{1}
}

func (x *PublishContentRequest) GetPublishedContent() *PublishedContent {
	if x != nil {
		return x.PublishedContent
	}
	return nil
}

func (x *PublishContentRequest) GetPublishMode() PublishMode {
	if x != nil {
		return x.PublishMode
	}
	return PublishMode_UNLISTED
}

type PublishContentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublishedContent *PublishedContent      `protobuf:"bytes,1,opt,name=published_content,proto3" json:"published_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishContentResponse) Reset() {
	*x = PublishContentResponse{}
	mi := &file_community_community_publish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentResponse) ProtoMessage() {}

func (x *PublishContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentResponse.ProtoReflect.Descriptor instead.
func (*PublishContentResponse) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{2}
}

func (x *PublishContentResponse) GetPublishedContent() *PublishedContent {
	if x != nil {
		return x.PublishedContent
	}
	return nil
}

type PublishContentDeleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublishedContent *PublishedContent      `protobuf:"bytes,1,opt,name=published_content,proto3" json:"published_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishContentDeleteRequest) Reset() {
	*x = PublishContentDeleteRequest{}
	mi := &file_community_community_publish_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentDeleteRequest) ProtoMessage() {}

func (x *PublishContentDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentDeleteRequest.ProtoReflect.Descriptor instead.
func (*PublishContentDeleteRequest) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{3}
}

func (x *PublishContentDeleteRequest) GetPublishedContent() *PublishedContent {
	if x != nil {
		return x.PublishedContent
	}
	return nil
}

type PublishContentDeleteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublishedContent *PublishedContent      `protobuf:"bytes,1,opt,name=published_content,proto3" json:"published_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishContentDeleteResponse) Reset() {
	*x = PublishContentDeleteResponse{}
	mi := &file_community_community_publish_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentDeleteResponse) ProtoMessage() {}

func (x *PublishContentDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentDeleteResponse.ProtoReflect.Descriptor instead.
func (*PublishContentDeleteResponse) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{4}
}

func (x *PublishContentDeleteResponse) GetPublishedContent() *PublishedContent {
	if x != nil {
		return x.PublishedContent
	}
	return nil
}

type PublishedContentSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,proto3" json:"community_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Sync          string                 `protobuf:"bytes,3,opt,name=sync,proto3" json:"sync,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedContentSearchRequest) Reset() {
	*x = PublishedContentSearchRequest{}
	mi := &file_community_community_publish_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedContentSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedContentSearchRequest) ProtoMessage() {}

func (x *PublishedContentSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedContentSearchRequest.ProtoReflect.Descriptor instead.
func (*PublishedContentSearchRequest) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{5}
}

func (x *PublishedContentSearchRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *PublishedContentSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PublishedContentSearchRequest) GetSync() string {
	if x != nil {
		return x.Sync
	}
	return ""
}

func (x *PublishedContentSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishedContentSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PublishedContentSearchResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Community     *Community                     `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	Next          *PublishedContentSearchRequest `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*PublishedContent            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedContentSearchResponse) Reset() {
	*x = PublishedContentSearchResponse{}
	mi := &file_community_community_publish_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedContentSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedContentSearchResponse) ProtoMessage() {}

func (x *PublishedContentSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_community_publish_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedContentSearchResponse.ProtoReflect.Descriptor instead.
func (*PublishedContentSearchResponse) Descriptor() ([]byte, []int) {
	return file_community_community_publish_proto_rawDescGZIP(), []int{6}
}

func (x *PublishedContentSearchResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

func (x *PublishedContentSearchResponse) GetNext() *PublishedContentSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *PublishedContentSearchResponse) GetItems() []*PublishedContent {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_community_community_publish_proto protoreflect.FileDescriptor

const file_community_community_publish_proto_rawDesc = "" +
	"\n" +
	"!community/community.publish.proto\x12\x14retrovibed.community\x1a\x19community/community.proto\"\xfb\x03\n" +
	"\x10PublishedContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcommunity_id\x18\x02 \x01(\tR\fcommunity_id\x12&\n" +
	"\x0eknown_media_id\x18\x03 \x01(\tR\x0eknown_media_id\x12\x1e\n" +
	"\n" +
	"magnet_uri\x18\x04 \x01(\tR\n" +
	"magnet_uri\x12\"\n" +
	"\fpublished_at\x18\x05 \x01(\tR\fpublished_at\x12\x1e\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\n" +
	"updated_at\x12 \n" +
	"\varchived_id\x18\b \x01(\tR\varchived_id\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1a\n" +
	"\bmimetype\x18\v \x01(\tR\bmimetype\x12(\n" +
	"\x0fencryption_seed\x18\f \x01(\tR\x0fencryption_seed\x12\x14\n" +
	"\x05bytes\x18\r \x01(\x04R\x05bytes\x12\x1f\n" +
	"\n" +
	"library_id\x18\xe8\a \x01(\tR\n" +
	"library_id\x12)\n" +
	"\x0foauth_google_id\x18\xe9\a \x01(\tR\x0foauth_google_idJ\x05\b\x0e\x10\xe8\a\"\xba\x01\n" +
	"\x15PublishContentRequest\x12T\n" +
	"\x11published_content\x18\x01 \x01(\v2&.retrovibed.community.PublishedContentR\x11published_content\x12E\n" +
	"\fpublish_mode\x18\x02 \x01(\x0e2!.retrovibed.community.PublishModeR\fpublish_modeJ\x04\b\x03\x10\x04\"n\n" +
	"\x16PublishContentResponse\x12T\n" +
	"\x11published_content\x18\x01 \x01(\v2&.retrovibed.community.PublishedContentR\x11published_content\"s\n" +
	"\x1bPublishContentDeleteRequest\x12T\n" +
	"\x11published_content\x18\x01 \x01(\v2&.retrovibed.community.PublishedContentR\x11published_content\"t\n" +
	"\x1cPublishContentDeleteResponse\x12T\n" +
	"\x11published_content\x18\x01 \x01(\v2&.retrovibed.community.PublishedContentR\x11published_content\"\xac\x01\n" +
	"\x1dPublishedContentSearchRequest\x12\"\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\fcommunity_id\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\tR\x04sync\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x04\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"\xe6\x01\n" +
	"\x1ePublishedContentSearchResponse\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunity\x12G\n" +
	"\x04next\x18\x02 \x01(\v23.retrovibed.community.PublishedContentSearchRequestR\x04next\x12<\n" +
	"\x05items\x18\x03 \x03(\v2&.retrovibed.community.PublishedContentR\x05itemsb\x06proto3"

var (
	file_community_community_publish_proto_rawDescOnce sync.Once
	file_community_community_publish_proto_rawDescData []byte
)

func file_community_community_publish_proto_rawDescGZIP() []byte {
	file_community_community_publish_proto_rawDescOnce.Do(func() {
		file_community_community_publish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_community_publish_proto_rawDesc), len(file_community_community_publish_proto_rawDesc)))
	})
	return file_community_community_publish_proto_rawDescData
}

var file_community_community_publish_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_community_community_publish_proto_goTypes = []any{
	(*PublishedContent)(nil),               // 0: retrovibed.community.PublishedContent
	(*PublishContentRequest)(nil),          // 1: retrovibed.community.PublishContentRequest
	(*PublishContentResponse)(nil),         // 2: retrovibed.community.PublishContentResponse
	(*PublishContentDeleteRequest)(nil),    // 3: retrovibed.community.PublishContentDeleteRequest
	(*PublishContentDeleteResponse)(nil),   // 4: retrovibed.community.PublishContentDeleteResponse
	(*PublishedContentSearchRequest)(nil),  // 5: retrovibed.community.PublishedContentSearchRequest
	(*PublishedContentSearchResponse)(nil), // 6: retrovibed.community.PublishedContentSearchResponse
	(PublishMode)(0),                       // 7: retrovibed.community.PublishMode
	(*Community)(nil),                      // 8: retrovibed.community.Community
}
var file_community_community_publish_proto_depIdxs = []int32{
	0, // 0: retrovibed.community.PublishContentRequest.published_content:type_name -> retrovibed.community.PublishedContent
	7, // 1: retrovibed.community.PublishContentRequest.publish_mode:type_name -> retrovibed.community.PublishMode
	0, // 2: retrovibed.community.PublishContentResponse.published_content:type_name -> retrovibed.community.PublishedContent
	0, // 3: retrovibed.community.PublishContentDeleteRequest.published_content:type_name -> retrovibed.community.PublishedContent
	0, // 4: retrovibed.community.PublishContentDeleteResponse.published_content:type_name -> retrovibed.community.PublishedContent
	8, // 5: retrovibed.community.PublishedContentSearchResponse.community:type_name -> retrovibed.community.Community
	5, // 6: retrovibed.community.PublishedContentSearchResponse.next:type_name -> retrovibed.community.PublishedContentSearchRequest
	0, // 7: retrovibed.community.PublishedContentSearchResponse.items:type_name -> retrovibed.community.PublishedContent
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_community_community_publish_proto_init() }
func file_community_community_publish_proto_init() {
	if File_community_community_publish_proto != nil {
		return
	}
	file_community_community_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_community_publish_proto_rawDesc), len(file_community_community_publish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_community_publish_proto_goTypes,
		DependencyIndexes: file_community_community_publish_proto_depIdxs,
		MessageInfos:      file_community_community_publish_proto_msgTypes,
	}.Build()
	File_community_community_publish_proto = out.File
	file_community_community_publish_proto_goTypes = nil
	file_community_community_publish_proto_depIdxs = nil
}
