version: "2"
linters:
  settings:
    errcheck: # https://golangci-lint.run/docs/linters/configuration/#errcheck
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      # check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      # Such cases aren't reported by default.
      # check-blank: true
      # To disable the errcheck built-in exclude list.
      # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
      # Default: false
      disable-default-exclusions: true
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - github.com/retrovibed/retrovibed/shallows/internal/httpx.AutoClose
        - github.com/retrovibed/retrovibed/shallows/internal/httpx.TryClose
        - github.com/retrovibed/retrovibed/shallows/internal/timex.NowAndEvery
        - (github.com/retrovibed/retrovibed/shallows/internal/sqlx.scanner[T]).Close
        - (github.com/retrovibed/retrovibed/shallows/internal/sqlx.scanner2[X, Y]).Close
        - (*github.com/retrovibed/retrovibed/shallows/internal/asyncx.Wakeup).Close
        - (*github.com/hashicorp/mdns.Server).Shutdown
        - (*github.com/fsnotify/fsnotify.Watcher).Close
        - (*os.File).Close
        - (io/fs.File).Close
        - (*compress/gzip.Writer).Close
        - (*mime/multipart.Part).Close
        - (*archive/tar.Writer).Close
        - (*compress/gzip.Reader).Close
        - (io.Writer).Write
        - (*io.PipeWriter).CloseWithError
        - (*io.PipeWriter).Close
        - (*database/sql.Rows).Close
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Println
        - (net.Conn).Close
        - (*github.com/james-lawrence/torrent.Client).Close
        - (*github.com/james-lawrence/torrent.Client).Stop
        - (*database/sql.DB).Close
        - (*github.com/mutablelogic/go-media/pkg/ffmpeg.Reader).Close
        - os.RemoveAll
        - os.Remove
      # Display function signature instead of selector.
      verbose: true
