// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta.authz.proto

package metaapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bearer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// START OF STANDARD FIELDS
	Id            string `protobuf:"bytes,1,opt,name=id,json=jti,proto3" json:"id,omitempty"`
	Issuer        string `protobuf:"bytes,2,opt,name=issuer,json=iss,proto3" json:"issuer,omitempty"`
	ProfileId     string `protobuf:"bytes,3,opt,name=profile_id,json=sub,proto3" json:"profile_id,omitempty"`
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sid,proto3" json:"session_id,omitempty"`
	Issued        int64  `protobuf:"varint,5,opt,name=issued,json=iat,proto3" json:"issued,omitempty"`
	Expires       int64  `protobuf:"varint,6,opt,name=expires,json=exp,proto3" json:"expires,omitempty"`
	NotBefore     int64  `protobuf:"varint,7,opt,name=not_before,json=nbf,proto3" json:"not_before,omitempty"` // END OF STANDARD FIELDS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bearer) Reset() {
	*x = Bearer{}
	mi := &file_meta_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bearer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bearer) ProtoMessage() {}

func (x *Bearer) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bearer.ProtoReflect.Descriptor instead.
func (*Bearer) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{0}
}

func (x *Bearer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bearer) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Bearer) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Bearer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Bearer) GetIssued() int64 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *Bearer) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Bearer) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// START OF STANDARD FIELDS
	Id             string `protobuf:"bytes,1,opt,name=id,json=jti,proto3" json:"id,omitempty"`
	Issuer         string `protobuf:"bytes,2,opt,name=issuer,json=iss,proto3" json:"issuer,omitempty"`
	ProfileId      string `protobuf:"bytes,3,opt,name=profile_id,json=sub,proto3" json:"profile_id,omitempty"`
	SessionId      string `protobuf:"bytes,4,opt,name=session_id,json=sid,proto3" json:"session_id,omitempty"`
	Issued         int64  `protobuf:"varint,5,opt,name=issued,json=iat,proto3" json:"issued,omitempty"`
	Expires        int64  `protobuf:"varint,6,opt,name=expires,json=exp,proto3" json:"expires,omitempty"`
	NotBefore      int64  `protobuf:"varint,7,opt,name=not_before,json=nbf,proto3" json:"not_before,omitempty"`
	Usermanagement bool   `protobuf:"varint,1000,opt,name=usermanagement,proto3" json:"usermanagement,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_meta_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Token) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Token) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Token) GetIssued() int64 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *Token) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Token) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *Token) GetUsermanagement() bool {
	if x != nil {
		return x.Usermanagement
	}
	return false
}

type AuthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzRequest) Reset() {
	*x = AuthzRequest{}
	mi := &file_meta_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzRequest) ProtoMessage() {}

func (x *AuthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzRequest.ProtoReflect.Descriptor instead.
func (*AuthzRequest) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{2}
}

type AuthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bearer        string                 `protobuf:"bytes,1,opt,name=bearer,proto3" json:"bearer,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzResponse) Reset() {
	*x = AuthzResponse{}
	mi := &file_meta_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzResponse) ProtoMessage() {}

func (x *AuthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzResponse.ProtoReflect.Descriptor instead.
func (*AuthzResponse) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{3}
}

func (x *AuthzResponse) GetBearer() string {
	if x != nil {
		return x.Bearer
	}
	return ""
}

func (x *AuthzResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthzGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzGrantRequest) Reset() {
	*x = AuthzGrantRequest{}
	mi := &file_meta_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzGrantRequest) ProtoMessage() {}

func (x *AuthzGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzGrantRequest.ProtoReflect.Descriptor instead.
func (*AuthzGrantRequest) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{4}
}

func (x *AuthzGrantRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthzGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzGrantResponse) Reset() {
	*x = AuthzGrantResponse{}
	mi := &file_meta_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzGrantResponse) ProtoMessage() {}

func (x *AuthzGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzGrantResponse.ProtoReflect.Descriptor instead.
func (*AuthzGrantResponse) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{5}
}

func (x *AuthzGrantResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthzRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzRevokeRequest) Reset() {
	*x = AuthzRevokeRequest{}
	mi := &file_meta_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzRevokeRequest) ProtoMessage() {}

func (x *AuthzRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzRevokeRequest.ProtoReflect.Descriptor instead.
func (*AuthzRevokeRequest) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{6}
}

func (x *AuthzRevokeRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthzRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzRevokeResponse) Reset() {
	*x = AuthzRevokeResponse{}
	mi := &file_meta_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzRevokeResponse) ProtoMessage() {}

func (x *AuthzRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzRevokeResponse.ProtoReflect.Descriptor instead.
func (*AuthzRevokeResponse) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{7}
}

func (x *AuthzRevokeResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthzProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzProfileRequest) Reset() {
	*x = AuthzProfileRequest{}
	mi := &file_meta_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzProfileRequest) ProtoMessage() {}

func (x *AuthzProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzProfileRequest.ProtoReflect.Descriptor instead.
func (*AuthzProfileRequest) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{8}
}

func (x *AuthzProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type AuthzProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzProfileResponse) Reset() {
	*x = AuthzProfileResponse{}
	mi := &file_meta_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzProfileResponse) ProtoMessage() {}

func (x *AuthzProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzProfileResponse.ProtoReflect.Descriptor instead.
func (*AuthzProfileResponse) Descriptor() ([]byte, []int) {
	return file_meta_authz_proto_rawDescGZIP(), []int{9}
}

func (x *AuthzProfileResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_meta_authz_proto protoreflect.FileDescriptor

const file_meta_authz_proto_rawDesc = "" +
	"\n" +
	"\x10meta.authz.proto\x12\x04meta\"\xa4\x01\n" +
	"\x06Bearer\x12\x0f\n" +
	"\x02id\x18\x01 \x01(\tR\x03jti\x12\x13\n" +
	"\x06issuer\x18\x02 \x01(\tR\x03iss\x12\x17\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\x03sub\x12\x17\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\x03sid\x12\x13\n" +
	"\x06issued\x18\x05 \x01(\x03R\x03iat\x12\x14\n" +
	"\aexpires\x18\x06 \x01(\x03R\x03exp\x12\x17\n" +
	"\n" +
	"not_before\x18\a \x01(\x03R\x03nbf\"\xd3\x01\n" +
	"\x05Token\x12\x0f\n" +
	"\x02id\x18\x01 \x01(\tR\x03jti\x12\x13\n" +
	"\x06issuer\x18\x02 \x01(\tR\x03iss\x12\x17\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\x03sub\x12\x17\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\x03sid\x12\x13\n" +
	"\x06issued\x18\x05 \x01(\x03R\x03iat\x12\x14\n" +
	"\aexpires\x18\x06 \x01(\x03R\x03exp\x12\x17\n" +
	"\n" +
	"not_before\x18\a \x01(\x03R\x03nbf\x12'\n" +
	"\x0eusermanagement\x18\xe8\a \x01(\bR\x0eusermanagementJ\x05\b\t\x10\xe8\a\"\x0e\n" +
	"\fAuthzRequest\"J\n" +
	"\rAuthzResponse\x12\x16\n" +
	"\x06bearer\x18\x01 \x01(\tR\x06bearer\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\v.meta.TokenR\x05token\"6\n" +
	"\x11AuthzGrantRequest\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.meta.TokenR\x05token\"7\n" +
	"\x12AuthzGrantResponse\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.meta.TokenR\x05token\"7\n" +
	"\x12AuthzRevokeRequest\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.meta.TokenR\x05token\"8\n" +
	"\x13AuthzRevokeResponse\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.meta.TokenR\x05token\"5\n" +
	"\x13AuthzProfileRequest\x12\x1e\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\n" +
	"profile_id\"9\n" +
	"\x14AuthzProfileResponse\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\v.meta.TokenR\x05tokenb\x06proto3"

var (
	file_meta_authz_proto_rawDescOnce sync.Once
	file_meta_authz_proto_rawDescData []byte
)

func file_meta_authz_proto_rawDescGZIP() []byte {
	file_meta_authz_proto_rawDescOnce.Do(func() {
		file_meta_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_authz_proto_rawDesc), len(file_meta_authz_proto_rawDesc)))
	})
	return file_meta_authz_proto_rawDescData
}

var file_meta_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_meta_authz_proto_goTypes = []any{
	(*Bearer)(nil),               // 0: meta.Bearer
	(*Token)(nil),                // 1: meta.Token
	(*AuthzRequest)(nil),         // 2: meta.AuthzRequest
	(*AuthzResponse)(nil),        // 3: meta.AuthzResponse
	(*AuthzGrantRequest)(nil),    // 4: meta.AuthzGrantRequest
	(*AuthzGrantResponse)(nil),   // 5: meta.AuthzGrantResponse
	(*AuthzRevokeRequest)(nil),   // 6: meta.AuthzRevokeRequest
	(*AuthzRevokeResponse)(nil),  // 7: meta.AuthzRevokeResponse
	(*AuthzProfileRequest)(nil),  // 8: meta.AuthzProfileRequest
	(*AuthzProfileResponse)(nil), // 9: meta.AuthzProfileResponse
}
var file_meta_authz_proto_depIdxs = []int32{
	1, // 0: meta.AuthzResponse.token:type_name -> meta.Token
	1, // 1: meta.AuthzGrantRequest.token:type_name -> meta.Token
	1, // 2: meta.AuthzGrantResponse.token:type_name -> meta.Token
	1, // 3: meta.AuthzRevokeRequest.token:type_name -> meta.Token
	1, // 4: meta.AuthzRevokeResponse.token:type_name -> meta.Token
	1, // 5: meta.AuthzProfileResponse.token:type_name -> meta.Token
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_meta_authz_proto_init() }
func file_meta_authz_proto_init() {
	if File_meta_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_authz_proto_rawDesc), len(file_meta_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_authz_proto_goTypes,
		DependencyIndexes: file_meta_authz_proto_depIdxs,
		MessageInfos:      file_meta_authz_proto_msgTypes,
	}.Build()
	File_meta_authz_proto = out.File
	file_meta_authz_proto_goTypes = nil
	file_meta_authz_proto_depIdxs = nil
}
