// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: meta.discovery.proto

package metaapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryDiagnostics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Ratio          uint32                 `protobuf:"varint,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Partitions     uint32                 `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Workloads      uint32                 `protobuf:"varint,4,opt,name=workloads,proto3" json:"workloads,omitempty"`
	LocalPartition string                 `protobuf:"bytes,5,opt,name=local_partition,proto3" json:"local_partition,omitempty"`
	Peers          uint64                 `protobuf:"varint,6,opt,name=peers,proto3" json:"peers,omitempty"`
	PeersDdisc     uint64                 `protobuf:"varint,7,opt,name=peers_ddisc,proto3" json:"peers_ddisc,omitempty"`
	PeersBep51     uint64                 `protobuf:"varint,8,opt,name=peers_bep51,proto3" json:"peers_bep51,omitempty"`
	UnknownHashes  uint64                 `protobuf:"varint,9,opt,name=unknown_hashes,proto3" json:"unknown_hashes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveryDiagnostics) Reset() {
	*x = DiscoveryDiagnostics{}
	mi := &file_meta_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryDiagnostics) ProtoMessage() {}

func (x *DiscoveryDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_meta_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryDiagnostics.ProtoReflect.Descriptor instead.
func (*DiscoveryDiagnostics) Descriptor() ([]byte, []int) {
	return file_meta_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryDiagnostics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DiscoveryDiagnostics) GetRatio() uint32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetPartitions() uint32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetWorkloads() uint32 {
	if x != nil {
		return x.Workloads
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetLocalPartition() string {
	if x != nil {
		return x.LocalPartition
	}
	return ""
}

func (x *DiscoveryDiagnostics) GetPeers() uint64 {
	if x != nil {
		return x.Peers
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetPeersDdisc() uint64 {
	if x != nil {
		return x.PeersDdisc
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetPeersBep51() uint64 {
	if x != nil {
		return x.PeersBep51
	}
	return 0
}

func (x *DiscoveryDiagnostics) GetUnknownHashes() uint64 {
	if x != nil {
		return x.UnknownHashes
	}
	return 0
}

type DiscoveryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discovery     *DiscoveryDiagnostics  `protobuf:"bytes,1,opt,name=discovery,proto3" json:"discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryMetricsResponse) Reset() {
	*x = DiscoveryMetricsResponse{}
	mi := &file_meta_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryMetricsResponse) ProtoMessage() {}

func (x *DiscoveryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryMetricsResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_meta_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryMetricsResponse) GetDiscovery() *DiscoveryDiagnostics {
	if x != nil {
		return x.Discovery
	}
	return nil
}

var File_meta_discovery_proto protoreflect.FileDescriptor

const file_meta_discovery_proto_rawDesc = "" +
	"\n" +
	"\x14meta.discovery.proto\x12\x04meta\"\xb0\x02\n" +
	"\x14DiscoveryDiagnostics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05ratio\x18\x02 \x01(\rR\x05ratio\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\rR\n" +
	"partitions\x12\x1c\n" +
	"\tworkloads\x18\x04 \x01(\rR\tworkloads\x12(\n" +
	"\x0flocal_partition\x18\x05 \x01(\tR\x0flocal_partition\x12\x14\n" +
	"\x05peers\x18\x06 \x01(\x04R\x05peers\x12 \n" +
	"\vpeers_ddisc\x18\a \x01(\x04R\vpeers_ddisc\x12 \n" +
	"\vpeers_bep51\x18\b \x01(\x04R\vpeers_bep51\x12&\n" +
	"\x0eunknown_hashes\x18\t \x01(\x04R\x0eunknown_hashes\"T\n" +
	"\x18DiscoveryMetricsResponse\x128\n" +
	"\tdiscovery\x18\x01 \x01(\v2\x1a.meta.DiscoveryDiagnosticsR\tdiscoveryb\x06proto3"

var (
	file_meta_discovery_proto_rawDescOnce sync.Once
	file_meta_discovery_proto_rawDescData []byte
)

func file_meta_discovery_proto_rawDescGZIP() []byte {
	file_meta_discovery_proto_rawDescOnce.Do(func() {
		file_meta_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_discovery_proto_rawDesc), len(file_meta_discovery_proto_rawDesc)))
	})
	return file_meta_discovery_proto_rawDescData
}

var file_meta_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_discovery_proto_goTypes = []any{
	(*DiscoveryDiagnostics)(nil),     // 0: meta.DiscoveryDiagnostics
	(*DiscoveryMetricsResponse)(nil), // 1: meta.DiscoveryMetricsResponse
}
var file_meta_discovery_proto_depIdxs = []int32{
	0, // 0: meta.DiscoveryMetricsResponse.discovery:type_name -> meta.DiscoveryDiagnostics
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meta_discovery_proto_init() }
func file_meta_discovery_proto_init() {
	if File_meta_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_discovery_proto_rawDesc), len(file_meta_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_discovery_proto_goTypes,
		DependencyIndexes: file_meta_discovery_proto_depIdxs,
		MessageInfos:      file_meta_discovery_proto_msgTypes,
	}.Build()
	File_meta_discovery_proto = out.File
	file_meta_discovery_proto_goTypes = nil
	file_meta_discovery_proto_depIdxs = nil
}
