name: linux release
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:

jobs:
  ios:
    name: linux-build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          sudo add-apt-repository ppa:egdaemon/duckdb
          sudo add-apt-repository ppa:egdaemon/eg
          sudo apt-get update
          sudo apt-get install eg podman
          sudo systemctl enable --now podman.service podman.socket
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true
      - name: build
        run: |
          sudo -E eg compute local -e GOOGLE_APPLICATION_CREDENTIALS -e GH_TOKEN release/linux
