name: debian release
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:

jobs:
  ios:
    name: debian-build
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo add-apt-repository ppa:egdaemon/duckdb
          sudo add-apt-repository ppa:egdaemon/eg
          sudo apt-get update
          sudo apt-get install eg podman
          sudo systemctl enable --now podman.service podman.socket
      - name: derp
        run: |
          echo "${{ secrets.EG_GPG_KEYRING_SEED }}" | base64 -w 0 | base64 -w 0
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: build
        run: |
          eg gpg keyring --seed="${{ secrets.EG_GPG_KEYRING_SEED }}"
          sudo -E eg compute local -e GOOGLE_APPLICATION_CREDENTIALS -e GH_TOKEN release/debian
